### ISSUE TITLE
android-8.1.0_r46 - com.android.phone crashes/reboots caused by com.sony.transmitpower.sensor

### ISSUE THREAD

**Issue by jamuir** [sonyxperiadev/bug_tracker#204]
**Platform:** yoshino
**Device:** maple
**Kernel version:** 4.4
**Android version:** 8.1.0_r46

**Description**
build and flash a maple device.

On first boot, a toast appears with the message "com.android.phone" has stopped.  If you continue to use the device, then it will sometimes reboot into recovery.

logcat:

```
10-12 13:00:18.751 D/AndroidRuntime( 2728): Shutting down VM
--------- beginning of crash
10-12 13:00:18.753 E/AndroidRuntime( 2728): FATAL EXCEPTION: main
10-12 13:00:18.753 E/AndroidRuntime( 2728): Process: com.android.phone, PID: 2728
10-12 13:00:18.753 E/AndroidRuntime( 2728): java.lang.RuntimeException: Unable to start receiver com.sony.transmitpower.sensor.FeatureIntentReceiver: java.lang.IllegalStateException: Sensor
10-12 13:00:18.753 E/AndroidRuntime( 2728):     at android.app.ActivityThread.handleReceiver(ActivityThread.java:3194)
10-12 13:00:18.753 E/AndroidRuntime( 2728):     at android.app.ActivityThread.-wrap17(Unknown Source:0)
10-12 13:00:18.753 E/AndroidRuntime( 2728):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672)
10-12 13:00:18.753 E/AndroidRuntime( 2728):     at android.os.Handler.dispatchMessage(Handler.java:106)
10-12 13:00:18.753 E/AndroidRuntime( 2728):     at android.os.Looper.loop(Looper.java:164)
10-12 13:00:18.753 E/AndroidRuntime( 2728):     at android.app.ActivityThread.main(ActivityThread.java:6494)
10-12 13:00:18.753 E/AndroidRuntime( 2728):     at java.lang.reflect.Method.invoke(Native Method)
10-12 13:00:18.753 E/AndroidRuntime( 2728):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
10-12 13:00:18.753 E/AndroidRuntime( 2728):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
10-12 13:00:18.753 E/AndroidRuntime( 2728): Caused by: java.lang.IllegalStateException: Sensor is null.
10-12 13:00:18.753 E/AndroidRuntime( 2728):     at com.sony.transmitpower.sensor.SensorBase.init(SensorBase.java:48)
10-12 13:00:18.753 E/AndroidRuntime( 2728):     at com.sony.transmitpower.sensor.Accelerometer.init(Accelerometer.java:68)
10-12 13:00:18.753 E/AndroidRuntime( 2728):     at com.sony.transmitpower.sensor.SensorFeature.init(SensorFeature.java:43)
10-12 13:00:18.753 E/AndroidRuntime( 2728):     at com.sony.transmitpower.sensor.FeatureIntentReceiver.onReceive(FeatureIntentReceiver.java:35)
10-12 13:00:18.753 E/AndroidRuntime( 2728):     at android.app.ActivityThread.handleReceiver(ActivityThread.java:3187)
10-12 13:00:18.753 E/AndroidRuntime( 2728):     ... 8 more
```

**Symptoms**
phone crashes, device spontaneously reboots.

**How to reproduce**
see above.

**Comment by jerpelea** [comment]
the issue is caused by the sensor service not beeing started corectly 

We have to backport the service start from Android 9

**Comment by jamuir** [comment]
Thanks for your quick reply.

Do you know what commits I can revert locally to get a working build?

**Comment by jerpelea** [comment]
https://github.com/sonyxperiadev/device-sony-common/commit/308ba92cf65c4961f070967f729376baef521781
https://github.com/sonyxperiadev/device-sony-common/commit/e8792bfabc1ead641bcddc33d77c6704ee55550a
have to be backported

**Comment by jamuir** [comment]
sepolicy needs to be updated:

```
$ grep avc dmesg.out           
[    4.289361] type=1400 audit(17112528.699:3): avc: denied { write } for pid=720 comm="macaddrsetup" name="bluetooth" dev="sda15" ino=524291 scontext=u:r:addrsetup:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[    4.289683] type=1400 audit(17112528.699:3): avc: denied { write } for pid=720 comm="macaddrsetup" name="bluetooth" dev="sda15" ino=524291 scontext=u:r:addrsetup:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[    4.289692] type=1400 audit(17112528.699:4): avc: denied { add_name } for pid=720 comm="macaddrsetup" name="bluetooth_bdaddr" scontext=u:r:addrsetup:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[    4.289747] type=1400 audit(17112528.699:4): avc: denied { add_name } for pid=720 comm="macaddrsetup" name="bluetooth_bdaddr" scontext=u:r:addrsetup:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[    4.289755] type=1400 audit(17112528.700:5): avc: denied { create } for pid=720 comm="macaddrsetup" name="bluetooth_bdaddr" scontext=u:r:addrsetup:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[    4.290368] type=1400 audit(17112528.700:5): avc: denied { create } for pid=720 comm="macaddrsetup" name="bluetooth_bdaddr" scontext=u:r:addrsetup:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[    4.290378] type=1400 audit(17112528.700:6): avc: denied { write open } for pid=720 comm="macaddrsetup" path="/data/vendor/bluetooth/bluetooth_bdaddr" dev="sda15" ino=524314 scontext=u:r:addrsetup:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[    4.291087] type=1400 audit(17112528.700:6): avc: denied { write open } for pid=720 comm="macaddrsetup" path="/data/vendor/bluetooth/bluetooth_bdaddr" dev="sda15" ino=524314 scontext=u:r:addrsetup:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[    4.291098] type=1400 audit(17112528.701:7): avc: denied { getattr } for pid=720 comm="macaddrsetup" path="/data/vendor/bluetooth/bluetooth_bdaddr" dev="sda15" ino=524314 scontext=u:r:addrsetup:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[    4.327167] type=1400 audit(17112528.701:7): avc: denied { getattr } for pid=720 comm="macaddrsetup" path="/data/vendor/bluetooth/bluetooth_bdaddr" dev="sda15" ino=524314 scontext=u:r:addrsetup:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[    4.327184] type=1400 audit(17112528.736:8): avc: denied { write } for pid=698 comm="sensors.qcom" name="sensors" dev="sda15" ino=524302 scontext=u:r:sensors:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[    4.327380] type=1400 audit(17112528.736:8): avc: denied { write } for pid=698 comm="sensors.qcom" name="sensors" dev="sda15" ino=524302 scontext=u:r:sensors:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[    4.327388] type=1400 audit(17112528.736:9): avc: denied { add_name } for pid=698 comm="sensors.qcom" name="sns.reg" scontext=u:r:sensors:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[    4.327452] type=1400 audit(17112528.736:9): avc: denied { add_name } for pid=698 comm="sensors.qcom" name="sns.reg" scontext=u:r:sensors:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[    4.327459] type=1400 audit(17112528.736:10): avc: denied { create } for pid=698 comm="sensors.qcom" name="sns.reg" scontext=u:r:sensors:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[    4.327511] type=1400 audit(17112528.736:10): avc: denied { create } for pid=698 comm="sensors.qcom" name="sns.reg" scontext=u:r:sensors:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[    4.327518] type=1400 audit(17112528.736:11): avc: denied { read write open } for pid=698 comm="sensors.qcom" path="/data/vendor/sensors/sns.reg" dev="sda15" ino=524315 scontext=u:r:sensors:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[    4.462165] type=1400 audit(17112528.736:11): avc: denied { read write open } for pid=698 comm="sensors.qcom" path="/data/vendor/sensors/sns.reg" dev="sda15" ino=524315 scontext=u:r:sensors:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[    4.462183] type=1400 audit(17112528.872:12): avc: denied { read } for pid=698 comm="sensors.qcom" name="sensors" dev="sda15" ino=524302 scontext=u:r:sensors:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[    4.462290] type=1400 audit(17112528.872:12): avc: denied { read } for pid=698 comm="sensors.qcom" name="sensors" dev="sda15" ino=524302 scontext=u:r:sensors:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[    4.462297] type=1400 audit(17112528.872:13): avc: denied { open } for pid=698 comm="sensors.qcom" path="/data/vendor/sensors" dev="sda15" ino=524302 scontext=u:r:sensors:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[    4.517762] type=1400 audit(17112528.872:13): avc: denied { open } for pid=698 comm="sensors.qcom" path="/data/vendor/sensors" dev="sda15" ino=524302 scontext=u:r:sensors:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[    4.517777] type=1400 audit(17112528.928:14): avc: denied { setattr } for pid=698 comm="sensors.qcom" name="sns.reg" dev="sda15" ino=524315 scontext=u:r:sensors:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[    4.517894] type=1400 audit(17112528.928:14): avc: denied { setattr } for pid=698 comm="sensors.qcom" name="sns.reg" dev="sda15" ino=524315 scontext=u:r:sensors:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[    4.517901] type=1400 audit(17112528.928:15): avc: denied { getattr } for pid=698 comm="sensors.qcom" path="/data/vendor/sensors/sns.reg" dev="sda15" ino=524315 scontext=u:r:sensors:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[    5.878268] type=1400 audit(17112528.928:15): avc: denied { getattr } for pid=698 comm="sensors.qcom" path="/data/vendor/sensors/sns.reg" dev="sda15" ino=524315 scontext=u:r:sensors:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[    5.878283] type=1400 audit(17112530.288:16): avc: denied { write } for pid=646 comm="HwBinder:646_1" name="delta" dev="sda15" ino=524294 scontext=u:r:hal_audio_default:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[    5.878365] type=1400 audit(17112530.288:16): avc: denied { write } for pid=646 comm="HwBinder:646_1" name="delta" dev="sda15" ino=524294 scontext=u:r:hal_audio_default:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[    5.878372] type=1400 audit(17112530.288:17): avc: denied { add_name } for pid=646 comm="HwBinder:646_1" name="Handset_cal.acdbdelta" scontext=u:r:hal_audio_default:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[    5.878425] type=1400 audit(17112530.288:17): avc: denied { add_name } for pid=646 comm="HwBinder:646_1" name="Handset_cal.acdbdelta" scontext=u:r:hal_audio_default:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[    5.878431] type=1400 audit(17112530.288:18): avc: denied { create } for pid=646 comm="HwBinder:646_1" name="Handset_cal.acdbdelta" scontext=u:r:hal_audio_default:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[    5.878502] type=1400 audit(17112530.288:18): avc: denied { create } for pid=646 comm="HwBinder:646_1" name="Handset_cal.acdbdelta" scontext=u:r:hal_audio_default:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[    5.878510] type=1400 audit(17112530.289:19): avc: denied { read append open } for pid=646 comm="HwBinder:646_1" path="/data/vendor/audio/acdbdata/delta/Handset_cal.acdbdelta" dev="sda15" ino=524317 scontext=u:r:hal_audio_default:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[    5.878563] type=1400 audit(17112530.289:19): avc: denied { read append open } for pid=646 comm="HwBinder:646_1" path="/data/vendor/audio/acdbdata/delta/Handset_cal.acdbdelta" dev="sda15" ino=524317 scontext=u:r:hal_audio_default:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[    5.878571] type=1400 audit(17112530.289:20): avc: denied { getattr } for pid=646 comm="HwBinder:646_1" path="/data/vendor/audio/acdbdata/delta/Handset_cal.acdbdelta" dev="sda15" ino=524317 scontext=u:r:hal_audio_default:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[    6.094874] type=1400 audit(17112530.289:20): avc: denied { getattr } for pid=646 comm="HwBinder:646_1" path="/data/vendor/audio/acdbdata/delta/Handset_cal.acdbdelta" dev="sda15" ino=524317 scontext=u:r:hal_audio_default:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[    6.094888] type=1400 audit(17112530.505:21): avc: denied { write } for pid=742 comm="rild" name="radio" dev="sda15" ino=524303 scontext=u:r:rild:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[    6.094977] type=1400 audit(17112530.505:21): avc: denied { write } for pid=742 comm="rild" name="radio" dev="sda15" ino=524303 scontext=u:r:rild:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[    6.094984] type=1400 audit(17112530.505:22): avc: denied { add_name } for pid=742 comm="rild" name="qcril.db" scontext=u:r:rild:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[    6.095074] type=1400 audit(17112530.505:22): avc: denied { add_name } for pid=742 comm="rild" name="qcril.db" scontext=u:r:rild:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[    6.095081] type=1400 audit(17112530.505:23): avc: denied { create } for pid=742 comm="rild" name="qcril.db" scontext=u:r:rild:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[    6.095134] type=1400 audit(17112530.505:23): avc: denied { create } for pid=742 comm="rild" name="qcril.db" scontext=u:r:rild:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[    6.095141] type=1400 audit(17112530.505:24): avc: denied { read write open } for pid=742 comm="rild" path="/data/vendor/radio/qcril.db" dev="sda15" ino=524324 scontext=u:r:rild:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[    6.095194] type=1400 audit(17112530.505:24): avc: denied { read write open } for pid=742 comm="rild" path="/data/vendor/radio/qcril.db" dev="sda15" ino=524324 scontext=u:r:rild:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[    6.095201] type=1400 audit(17112530.505:25): avc: denied { getattr } for pid=741 comm="rild" path="/data/vendor/radio/qcril.db" dev="sda15" ino=524324 scontext=u:r:rild:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[    6.095252] type=1400 audit(17112530.505:25): avc: denied { getattr } for pid=741 comm="rild" path="/data/vendor/radio/qcril.db" dev="sda15" ino=524324 scontext=u:r:rild:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[    6.095258] type=1400 audit(17112530.505:26): avc: denied { ioctl } for pid=741 comm="rild" path="/data/vendor/radio/qcril.db" dev="sda15" ino=524324 ioctlcmd=f50c scontext=u:r:rild:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[    6.097389] type=1400 audit(17112530.505:26): avc: denied { ioctl } for pid=741 comm="rild" path="/data/vendor/radio/qcril.db" dev="sda15" ino=524324 ioctlcmd=f50c scontext=u:r:rild:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[    6.097401] type=1400 audit(17112530.507:27): avc: denied { lock } for pid=742 comm="rild" path="/data/vendor/radio/qcril.db" dev="sda15" ino=524324 scontext=u:r:rild:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[    6.115626] type=1400 audit(17112530.507:27): avc: denied { lock } for pid=742 comm="rild" path="/data/vendor/radio/qcril.db" dev="sda15" ino=524324 scontext=u:r:rild:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[    6.115635] type=1400 audit(17112530.526:28): avc: denied { read } for pid=741 comm="rild" name="radio" dev="sda15" ino=524303 scontext=u:r:rild:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[    6.115703] type=1400 audit(17112530.526:28): avc: denied { read } for pid=741 comm="rild" name="radio" dev="sda15" ino=524303 scontext=u:r:rild:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[    6.115710] type=1400 audit(17112530.526:29): avc: denied { open } for pid=741 comm="rild" path="/data/vendor/radio" dev="sda15" ino=524303 scontext=u:r:rild:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[    6.124130] type=1400 audit(17112530.526:29): avc: denied { open } for pid=741 comm="rild" path="/data/vendor/radio" dev="sda15" ino=524303 scontext=u:r:rild:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[    6.124140] type=1400 audit(17112530.534:30): avc: denied { remove_name } for pid=741 comm="rild" name="qcril.db-journal" dev="sda15" ino=524325 scontext=u:r:rild:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[    6.124235] type=1400 audit(17112530.534:30): avc: denied { remove_name } for pid=741 comm="rild" name="qcril.db-journal" dev="sda15" ino=524325 scontext=u:r:rild:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[    6.124242] type=1400 audit(17112530.534:31): avc: denied { unlink } for pid=741 comm="rild" name="qcril.db-journal" dev="sda15" ino=524325 scontext=u:r:rild:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[    7.104429] type=1400 audit(17112530.534:31): avc: denied { unlink } for pid=741 comm="rild" name="qcril.db-journal" dev="sda15" ino=524325 scontext=u:r:rild:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[    7.104442] type=1400 audit(17112531.515:32): avc: denied { lock } for pid=742 comm="rild" path="/data/vendor/radio/qcril.db" dev="sda15" ino=524324 scontext=u:r:rild:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[    7.105068] type=1400 audit(17112531.515:32): avc: denied { lock } for pid=742 comm="rild" path="/data/vendor/radio/qcril.db" dev="sda15" ino=524324 scontext=u:r:rild:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[    7.105081] type=1400 audit(17112531.515:33): avc: denied { getattr } for pid=742 comm="rild" path="/data/vendor/radio/qcril.db" dev="sda15" ino=524324 scontext=u:r:rild:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[    7.106291] type=1400 audit(17112531.515:33): avc: denied { getattr } for pid=742 comm="rild" path="/data/vendor/radio/qcril.db" dev="sda15" ino=524324 scontext=u:r:rild:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[    7.106302] type=1400 audit(17112531.517:34): avc: denied { write } for pid=742 comm="rild" name="radio" dev="sda15" ino=524303 scontext=u:r:rild:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[    7.106397] type=1400 audit(17112531.517:34): avc: denied { write } for pid=742 comm="rild" name="radio" dev="sda15" ino=524303 scontext=u:r:rild:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[    7.106404] type=1400 audit(17112531.517:35): avc: denied { add_name } for pid=742 comm="rild" name="qcril.db-journal" scontext=u:r:rild:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[    7.106457] type=1400 audit(17112531.517:35): avc: denied { add_name } for pid=742 comm="rild" name="qcril.db-journal" scontext=u:r:rild:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[    7.106464] type=1400 audit(17112531.517:36): avc: denied { create } for pid=742 comm="rild" name="qcril.db-journal" scontext=u:r:rild:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[    7.106690] type=1400 audit(17112531.517:36): avc: denied { create } for pid=742 comm="rild" name="qcril.db-journal" scontext=u:r:rild:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[    7.106698] type=1400 audit(17112531.517:37): avc: denied { read write open } for pid=742 comm="rild" path="/data/vendor/radio/qcril.db-journal" dev="sda15" ino=524329 scontext=u:r:rild:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[    7.140872] type=1400 audit(17112531.517:37): avc: denied { read write open } for pid=742 comm="rild" path="/data/vendor/radio/qcril.db-journal" dev="sda15" ino=524329 scontext=u:r:rild:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[    7.140886] type=1400 audit(17112531.551:38): avc: denied { read } for pid=742 comm="rild" name="radio" dev="sda15" ino=524303 scontext=u:r:rild:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[    7.140991] type=1400 audit(17112531.551:38): avc: denied { read } for pid=742 comm="rild" name="radio" dev="sda15" ino=524303 scontext=u:r:rild:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[    7.140999] type=1400 audit(17112531.551:39): avc: denied { open } for pid=742 comm="rild" path="/data/vendor/radio" dev="sda15" ino=524303 scontext=u:r:rild:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[    7.144781] type=1400 audit(17112531.551:39): avc: denied { open } for pid=742 comm="rild" path="/data/vendor/radio" dev="sda15" ino=524303 scontext=u:r:rild:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[    7.144795] type=1400 audit(17112531.555:40): avc: denied { remove_name } for pid=742 comm="rild" name="qcril.db-journal" dev="sda15" ino=524329 scontext=u:r:rild:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[    7.144903] type=1400 audit(17112531.555:40): avc: denied { remove_name } for pid=742 comm="rild" name="qcril.db-journal" dev="sda15" ino=524329 scontext=u:r:rild:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[    7.144910] type=1400 audit(17112531.555:41): avc: denied { unlink } for pid=742 comm="rild" name="qcril.db-journal" dev="sda15" ino=524329 scontext=u:r:rild:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[    7.218929] type=1400 audit(17112531.555:41): avc: denied { unlink } for pid=742 comm="rild" name="qcril.db-journal" dev="sda15" ino=524329 scontext=u:r:rild:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[    7.218943] type=1400 audit(17112531.629:42): avc: denied { ioctl } for pid=742 comm="rild" path="/data/vendor/radio/qcril.db" dev="sda15" ino=524324 ioctlcmd=f50c scontext=u:r:rild:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[   67.975288] type=1400 audit(17112531.629:42): avc: denied { ioctl } for pid=742 comm="rild" path="/data/vendor/radio/qcril.db" dev="sda15" ino=524324 ioctlcmd=f50c scontext=u:r:rild:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[   67.975303] type=1400 audit(1539364716.205:43): avc: denied { write } for pid=647 comm="bluetooth@1.0-s" name="bluetooth" dev="sda15" ino=524291 scontext=u:r:hal_bluetooth_default:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[   67.975412] type=1400 audit(1539364716.205:43): avc: denied { write } for pid=647 comm="bluetooth@1.0-s" name="bluetooth" dev="sda15" ino=524291 scontext=u:r:hal_bluetooth_default:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[   67.975419] type=1400 audit(1539364716.205:44): avc: denied { add_name } for pid=647 comm="bluetooth@1.0-s" name="bt_fw_version.txt" scontext=u:r:hal_bluetooth_default:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[   67.975475] type=1400 audit(1539364716.205:44): avc: denied { add_name } for pid=647 comm="bluetooth@1.0-s" name="bt_fw_version.txt" scontext=u:r:hal_bluetooth_default:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1
[   67.975482] type=1400 audit(1539364716.205:45): avc: denied { create } for pid=647 comm="bluetooth@1.0-s" name="bt_fw_version.txt" scontext=u:r:hal_bluetooth_default:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[   67.975545] type=1400 audit(1539364716.205:45): avc: denied { create } for pid=647 comm="bluetooth@1.0-s" name="bt_fw_version.txt" scontext=u:r:hal_bluetooth_default:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[   67.975553] type=1400 audit(1539364716.206:46): avc: denied { write open } for pid=647 comm="bluetooth@1.0-s" path="/data/vendor/bluetooth/bt_fw_version.txt" dev="sda15" ino=524329 scontext=u:r:hal_bluetooth_default:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[   67.975607] type=1400 audit(1539364716.206:46): avc: denied { write open } for pid=647 comm="bluetooth@1.0-s" path="/data/vendor/bluetooth/bt_fw_version.txt" dev="sda15" ino=524329 scontext=u:r:hal_bluetooth_default:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[   67.975614] type=1400 audit(1539364716.206:47): avc: denied { getattr } for pid=647 comm="bluetooth@1.0-s" path="/data/vendor/bluetooth/bt_fw_version.txt" dev="sda15" ino=524329 scontext=u:r:hal_bluetooth_default:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[   68.425267] type=1400 audit(1539364716.206:47): avc: denied { getattr } for pid=647 comm="bluetooth@1.0-s" path="/data/vendor/bluetooth/bt_fw_version.txt" dev="sda15" ino=524329 scontext=u:r:hal_bluetooth_default:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
[   68.425282] type=1400 audit(1539364716.660:48): avc: denied { read append } for pid=647 comm="bluetooth@1.0-s" name="bt_fw_version.txt" dev="sda15" ino=524329 scontext=u:r:hal_bluetooth_default:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1
```
