### ISSUE TITLE
Camera crash on Xperia X android 8.1.0

### ISSUE THREAD

**Issue by XperiaDeveloper** [sonyxperiadev/bug_tracker#265]
**Platform:** Loire
**Device:** X
**Kernel version:** 4.4
**Android version:** 8.1.0

**Description**
I built Sony Xperia X for Android 8.1.0 and phone crashes after flashing on first boot if no SIM card is inserted to the device.
Popup: "com.android.phone has stopped"

Snippet from Logcat: 

> --------- beginning of crash
> 12-07 13:03:45.871  2940  2940 E AndroidRuntime: FATAL EXCEPTION: main
> 12-07 13:03:45.871  2940  2940 E AndroidRuntime: Process: com.android.phone, PID: 2940
> 12-07 13:03:45.871  2940  2940 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver com.sony.transmitpower.sensor.FeatureIntentReceiver: java.lang.IllegalStateException: Sensor is null.
> 12-07 13:03:45.871  2940  2940 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3194)
> 12-07 13:03:45.871  2940  2940 E AndroidRuntime: 	at android.app.ActivityThread.-wrap17(Unknown Source:0)
> 12-07 13:03:45.871  2940  2940 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672)
> 12-07 13:03:45.871  2940  2940 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 12-07 13:03:45.871  2940  2940 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
> 12-07 13:03:45.871  2940  2940 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
> 12-07 13:03:45.871  2940  2940 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
> 12-07 13:03:45.871  2940  2940 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
> 12-07 13:03:45.871  2940  2940 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
> 12-07 13:03:45.871  2940  2940 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Sensor is null.
> 12-07 13:03:45.871  2940  2940 E AndroidRuntime: 	at com.sony.transmitpower.sensor.SensorBase.init(SensorBase.java:48)
> 12-07 13:03:45.871  2940  2940 E AndroidRuntime: 	at com.sony.transmitpower.sensor.Accelerometer.init(Accelerometer.java:68)
> 12-07 13:03:45.871  2940  2940 E AndroidRuntime: 	at com.sony.transmitpower.sensor.SensorFeature.init(SensorFeature.java:43)
> 12-07 13:03:45.871  2940  2940 E AndroidRuntime: 	at com.sony.transmitpower.sensor.FeatureIntentReceiver.onReceive(FeatureIntentReceiver.java:35)
> 12-07 13:03:45.871  2940  2940 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3187)
> 12-07 13:03:45.871  2940  2940 E AndroidRuntime: 	... 8 more
> 12-07 13:03:45.882  1941  2918 V RescueParty: Disabled because of active USB connection
> 12-07 13:03:45.893  1941  2106 I ActivityManager: Showing crash dialog for package com.android.phone u0

Here some more detail about the issue: 

1. Build for Sony Xperia X as described here: [guide](https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-nougat-8-1-oreo-4-4)
  - Kernel 4.4
  - Binary set v16
  - Insert no SIM card
 - Build userdebug or user
2. Crash happens on first boot
3. Full logcat:
[logcat.log](https://github.com/sonyxperiadev/transpower/files/2676221/logcat.log)

**Comment by jerpelea** [comment]
it looks like the sensors are not started 
I will take a look

**Comment by yshui** [comment]
I am seeing a similar error on Xperia X compact
