### ISSUE TITLE
Primary camera does not save video

### ISSUE THREAD

**Issue by dimitar10** [sonyxperiadev/bug_tracker#30]
**Platform:** loire, tone, yoshino
**Device:** suzu, kagura, maple
**Kernel version:** 4.4 (prebuilt, Nov 8)
**Android version:** 7.1.1 and 8.0.0
**Firmware version:** v05

**Description**
Primary camera records video, but it does not save it. The issue happens quite often. It appears on all three platforms, or at least on the three aforementioned devices. Behaviour is the same.

**Symptoms**
After the user stops recording video, the camera app does not save it to a file, and neither a new thumbnail of the new video appears. Sometimes the camera app UI will lag before not saving the video. 

**How to reproduce**
1. Open Camera App
2. Choose Video
3. Click the `Record Video` button on the screen, record for some time, and press the `Stop` button
**or** 
3. Press and hold the `Camera` button on the side of the device, and release it after some time.

**Logcat**

```
05-15 09:45:02.150 E/MediaRecorder( 3106): stop failed: -1007
05-15 09:45:02.153 E/CAM_VideoModule( 3106): stop fail
05-15 09:45:02.153 E/CAM_VideoModule( 3106): java.lang.RuntimeException: stop failed.
05-15 09:45:02.153 E/CAM_VideoModule( 3106): 	at android.media.MediaRecorder.stop(Native Method)
05-15 09:45:02.153 E/CAM_VideoModule( 3106): 	at com.android.camera.VideoModule.stopVideoRecording(VideoModule.java:1489)
05-15 09:45:02.153 E/CAM_VideoModule( 3106): 	at com.android.camera.VideoModule.onStopVideoRecording(VideoModule.java:659)
05-15 09:45:02.153 E/CAM_VideoModule( 3106): 	at com.android.camera.VideoModule.onShutterButtonClick(VideoModule.java:700)
05-15 09:45:02.153 E/CAM_VideoModule( 3106): 	at com.android.camera.VideoModule.onKeyUp(VideoModule.java:1060)
05-15 09:45:02.153 E/CAM_VideoModule( 3106): 	at com.android.camera.CameraActivity.onKeyUp(CameraActivity.java:2234)
05-15 09:45:02.153 E/CAM_VideoModule( 3106): 	at android.view.KeyEvent.dispatch(KeyEvent.java:2712)
05-15 09:45:02.153 E/CAM_VideoModule( 3106): 	at android.app.Activity.dispatchKeyEvent(Activity.java:3257)
05-15 09:45:02.153 E/CAM_VideoModule( 3106): 	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:351)
05-15 09:45:02.153 E/CAM_VideoModule( 3106): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4714)
05-15 09:45:02.153 E/CAM_VideoModule( 3106): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4586)
05-15 09:45:02.153 E/CAM_VideoModule( 3106): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4128)
05-15 09:45:02.153 E/CAM_VideoModule( 3106): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4181)
05-15 09:45:02.153 E/CAM_VideoModule( 3106): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4147)
05-15 09:45:02.153 E/CAM_VideoModule( 3106): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4274)
05-15 09:45:02.153 E/CAM_VideoModule( 3106): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4155)
05-15 09:45:02.153 E/CAM_VideoModule( 3106): 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4331)
05-15 09:45:02.153 E/CAM_VideoModule( 3106): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4128)
05-15 09:45:02.153 E/CAM_VideoModule( 3106): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4181)
05-15 09:45:02.153 E/CAM_VideoModule( 3106): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4147)
05-15 09:45:02.153 E/CAM_VideoModule( 3106): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4155)
05-15 09:45:02.153 E/CAM_VideoModule( 3106): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4128)
05-15 09:45:02.153 E/CAM_VideoModule( 3106): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4181)
05-15 09:45:02.153 E/CAM_VideoModule( 3106): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4147)
05-15 09:45:02.153 E/CAM_VideoModule( 3106): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4307)
05-15 09:45:02.153 E/CAM_VideoModule( 3106): 	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4468)
05-15 09:45:02.153 E/CAM_VideoModule( 3106): 	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2435)
05-15 09:45:02.153 E/CAM_VideoModule( 3106): 	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1998)
05-15 09:45:02.153 E/CAM_VideoModule( 3106): 	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1989)
05-15 09:45:02.153 E/CAM_VideoModule( 3106): 	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2412)
05-15 09:45:02.153 E/CAM_VideoModule( 3106): 	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
05-15 09:45:02.153 E/CAM_VideoModule( 3106): 	at android.os.MessageQueue.nativePollOnce(Native Method)
05-15 09:45:02.153 E/CAM_VideoModule( 3106): 	at android.os.MessageQueue.next(MessageQueue.java:325)
05-15 09:45:02.153 E/CAM_VideoModule( 3106): 	at android.os.Looper.loop(Looper.java:142)
05-15 09:45:02.153 E/CAM_VideoModule( 3106): 	at android.app.ActivityThread.main(ActivityThread.java:6541)
05-15 09:45:02.153 E/CAM_VideoModule( 3106): 	at java.lang.reflect.Method.invoke(Native Method)
05-15 09:45:02.153 E/CAM_VideoModule( 3106): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
05-15 09:45:02.153 E/CAM_VideoModule( 3106): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
05-15 09:45:02.156 V/CAM_VideoModule( 3106): Deleting video /storage/emulated/0/DCIM/Camera/VID_19710515_094451.mp4.tmp
05-15 09:45:02.159 D/CAM_OrientMgrImpl( 3106): unlock orientation
05-15 09:45:02.162 I/CAM_VideoModule( 3106): Releasing media recorder.


```

**Comment by kholk** [comment]
I confirm the issue on Loire Suzu and Yoshino Maple.

**Comment by oshmoun** [comment]
This seems to affect  video recording generally, not just primary camera

**Comment by oshmoun** [comment]
Solved with https://github.com/sonyxperiadev/kernel/pull/1509

**Comment by kholk** [comment]
Confirmed. This issue can be closed.
