### ISSUE TITLE
[Discovery] Unable to build android-9.0.0_r30

### ISSUE THREAD

**Issue by ploth** [sonyxperiadev/bug_tracker#304]
**Platform:** Nile
**Device:** Discovery, XA2 Ultra, H3213
**Kernel version:** irrelevant
**Android version:** android-9.0.0_r30

**Description**
Unable to build android-9.0.0_r30 branch for for H3213 discovery

**Symptoms**

```zsh
[ 74% 78489/105589] target Turbine: colorpicker
FAILED: out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/classes-turbine.jar 
/bin/bash -c "(rm -rf out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates//classes-turbine ) && (mkdir out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates//classes-turbine ) && (if [ -s out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/java-source-list -o -n \" out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/aapt2.srcjar\" ] ; then prebuilts/jdk/jdk9/linux-x86/bin/java -jar out/soong/host/linux-x86/framework/turbine.jar --output out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/classes-turbine.jar.premerged --temp_dir out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates//classes-turbine --sources \\@out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/java-source-list --source_jars  out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/aapt2.srcjar --javacopts  -source 1.7 -target 1.7  -Xmaxerrs 9999999 -encoding UTF-8 -sourcepath \"\" -g -XDskipDuplicateBridges=true -XDstringConcat=inline --bootclasspath out/target/common/obj/JAVA_LIBRARIES/sdk_v15_intermediates/classes-header.jar:out/target/common/obj/JAVA_LIBRARIES/core-lambda-stubs_intermediates/classes-header.jar  || ( rm -rf out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates//classes-turbine ; exit 41 ) && out/soong/host/linux-x86/bin/merge_zips -j --ignore-duplicates -stripDir META-INF out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/classes-turbine.jar.tmp out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/classes-turbine.jar.premerged   ; else out/soong/host/linux-x86/bin/merge_zips -j --ignore-duplicates -stripDir META-INF out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/classes-turbine.jar.tmp   ; fi ) && (prebuilts/build-tools/linux-x86/bin/ziptime out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/classes-turbine.jar.tmp ) && (if cmp -s out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/classes-turbine.jar.tmp out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/classes-turbine.jar ; then rm out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/classes-turbine.jar.tmp ; else mv out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/classes-turbine.jar.tmp out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/classes-turbine.jar ; fi )"
Exception in thread "main" java.lang.IllegalArgumentException: Multiple entries with same key: com/android/colorpicker/R$dimen=com.google.turbine.binder.bound.SourceBoundClass@2b552920 and com/android/colorpicker/R$dimen=com.google.turbine.binder.bound.SourceBoundClass@2758fe70
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:186)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:102)
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:88)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:359)
	at com.google.turbine.binder.env.SimpleEnv$Builder.build(SimpleEnv.java:48)
	at com.google.turbine.binder.Binder.bindSourceBoundClasses(Binder.java:124)
	at com.google.turbine.binder.Binder.bind(Binder.java:74)
	at com.google.turbine.main.Main.compile(Main.java:76)
	at com.google.turbine.main.Main.compile(Main.java:61)
	at com.google.turbine.main.Main.main(Main.java:56)
[ 74% 78490/105589] target Turbine: android-opt-timezonepicker
FAILED: out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/classes-turbine.jar 
/bin/bash -c "(rm -rf out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates//classes-turbine ) && (mkdir out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates//classes-turbine ) && (if [ -s out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/java-source-list -o -n \" out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/aapt.srcjar\" ] ; then prebuilts/jdk/jdk9/linux-x86/bin/java -jar out/soong/host/linux-x86/framework/turbine.jar --output out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/classes-turbine.jar.premerged --temp_dir out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates//classes-turbine --sources \\@out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/java-source-list --source_jars  out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/aapt.srcjar --javacopts  -source 1.7 -target 1.7  -Xmaxerrs 9999999 -encoding UTF-8 -sourcepath \"\" -g -XDskipDuplicateBridges=true -XDstringConcat=inline --bootclasspath out/target/common/obj/JAVA_LIBRARIES/sdk_v17_intermediates/classes-header.jar:out/target/common/obj/JAVA_LIBRARIES/core-lambda-stubs_intermediates/classes-header.jar  || ( rm -rf out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates//classes-turbine ; exit 41 ) && out/soong/host/linux-x86/bin/merge_zips -j --ignore-duplicates -stripDir META-INF out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/classes-turbine.jar.tmp out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/classes-turbine.jar.premerged   ; else out/soong/host/linux-x86/bin/merge_zips -j --ignore-duplicates -stripDir META-INF out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/classes-turbine.jar.tmp   ; fi ) && (prebuilts/build-tools/linux-x86/bin/ziptime out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/classes-turbine.jar.tmp ) && (if cmp -s out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/classes-turbine.jar.tmp out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/classes-turbine.jar ; then rm out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/classes-turbine.jar.tmp ; else mv out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/classes-turbine.jar.tmp out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/classes-turbine.jar ; fi )"
Exception in thread "main" java.lang.IllegalArgumentException: Multiple entries with same key: com/android/timezonepicker/R$array=com.google.turbine.binder.bound.SourceBoundClass@1f36e637 and com/android/timezonepicker/R$array=com.google.turbine.binder.bound.SourceBoundClass@578486a3
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:186)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:102)
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:88)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:359)
	at com.google.turbine.binder.env.SimpleEnv$Builder.build(SimpleEnv.java:48)
	at com.google.turbine.binder.Binder.bindSourceBoundClasses(Binder.java:124)
	at com.google.turbine.binder.Binder.bind(Binder.java:74)
	at com.google.turbine.main.Main.compile(Main.java:76)
	at com.google.turbine.main.Main.compile(Main.java:61)
	at com.google.turbine.main.Main.main(Main.java:56)
[ 74% 78497/105589] //external/eigen/blas:libF77blas clang++ double.cpp
ninja: build stopped: subcommand failed.
16:45:24 ninja failed with: exit status 1

#### failed to build some targets (02:15:04 (hh:mm:ss)) ####
```

**How to reproduce**
Same dockerfile as in #238 used. Called `source build/envsetup.sh && lunch` and `make -j9`

**Comment by ploth** [comment]
I got additional? information after starting the build again

```zsh
root@d4673f1b3488:/mnt# make -j9
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=9
TARGET_PRODUCT=aosp_h3213
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=cortex-a53
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv8-a
TARGET_2ND_CPU_VARIANT=cortex-a53
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.16.18-gentoo-x86_64-Ubuntu-16.04.5-LTS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=PQ1A.190105.004
OUT_DIR=out
============================================
ninja: no work to do.
ninja: no work to do.
wildcard(out/target/product/discovery/clean_steps.mk) was changed, regenerating...
No need to regenerate ninja file
[  0% 3/27094] target Turbine: colorpicker
FAILED: out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/classes-turbine.jar 
/bin/bash -c "(rm -rf out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates//classes-turbine ) && (mkdir out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates//classes-turbine ) && (if [ -s out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/java-source-list -o -n \" out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/aapt2.srcjar\" ] ; then prebuilts/jdk/jdk9/linux-x86/bin/java -jar out/soong/host/linux-x86/framework/turbine.jar --output out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/classes-turbine.jar.premerged --temp_dir out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates//classes-turbine --sources \\@out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/java-source-list --source_jars  out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/aapt2.srcjar --javacopts  -source 1.7 -target 1.7  -Xmaxerrs 9999999 -encoding UTF-8 -sourcepath \"\" -g -XDskipDuplicateBridges=true -XDstringConcat=inline --bootclasspath out/target/common/obj/JAVA_LIBRARIES/sdk_v15_intermediates/classes-header.jar:out/target/common/obj/JAVA_LIBRARIES/core-lambda-stubs_intermediates/classes-header.jar  || ( rm -rf out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates//classes-turbine ; exit 41 ) && out/soong/host/linux-x86/bin/merge_zips -j --ignore-duplicates -stripDir META-INF out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/classes-turbine.jar.tmp out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/classes-turbine.jar.premerged   ; else out/soong/host/linux-x86/bin/merge_zips -j --ignore-duplicates -stripDir META-INF out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/classes-turbine.jar.tmp   ; fi ) && (prebuilts/build-tools/linux-x86/bin/ziptime out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/classes-turbine.jar.tmp ) && (if cmp -s out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/classes-turbine.jar.tmp out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/classes-turbine.jar ; then rm out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/classes-turbine.jar.tmp ; else mv out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/classes-turbine.jar.tmp out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/classes-turbine.jar ; fi )"
Exception in thread "main" java.lang.IllegalArgumentException: Multiple entries with same key: com/android/colorpicker/R$dimen=com.google.turbine.binder.bound.SourceBoundClass@627551fb and com/android/colorpicker/R$dimen=com.google.turbine.binder.bound.SourceBoundClass@2b552920
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:186)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:102)
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:88)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:359)
	at com.google.turbine.binder.env.SimpleEnv$Builder.build(SimpleEnv.java:48)
	at com.google.turbine.binder.Binder.bindSourceBoundClasses(Binder.java:124)
	at com.google.turbine.binder.Binder.bind(Binder.java:74)
	at com.google.turbine.main.Main.compile(Main.java:76)
	at com.google.turbine.main.Main.compile(Main.java:61)
	at com.google.turbine.main.Main.main(Main.java:56)
[  0% 4/27094] target Turbine: android-opt-timezonepicker
FAILED: out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/classes-turbine.jar 
/bin/bash -c "(rm -rf out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates//classes-turbine ) && (mkdir out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates//classes-turbine ) && (if [ -s out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/java-source-list -o -n \" out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/aapt.srcjar\" ] ; then prebuilts/jdk/jdk9/linux-x86/bin/java -jar out/soong/host/linux-x86/framework/turbine.jar --output out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/classes-turbine.jar.premerged --temp_dir out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates//classes-turbine --sources \\@out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/java-source-list --source_jars  out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/aapt.srcjar --javacopts  -source 1.7 -target 1.7  -Xmaxerrs 9999999 -encoding UTF-8 -sourcepath \"\" -g -XDskipDuplicateBridges=true -XDstringConcat=inline --bootclasspath out/target/common/obj/JAVA_LIBRARIES/sdk_v17_intermediates/classes-header.jar:out/target/common/obj/JAVA_LIBRARIES/core-lambda-stubs_intermediates/classes-header.jar  || ( rm -rf out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates//classes-turbine ; exit 41 ) && out/soong/host/linux-x86/bin/merge_zips -j --ignore-duplicates -stripDir META-INF out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/classes-turbine.jar.tmp out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/classes-turbine.jar.premerged   ; else out/soong/host/linux-x86/bin/merge_zips -j --ignore-duplicates -stripDir META-INF out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/classes-turbine.jar.tmp   ; fi ) && (prebuilts/build-tools/linux-x86/bin/ziptime out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/classes-turbine.jar.tmp ) && (if cmp -s out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/classes-turbine.jar.tmp out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/classes-turbine.jar ; then rm out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/classes-turbine.jar.tmp ; else mv out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/classes-turbine.jar.tmp out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/classes-turbine.jar ; fi )"
Exception in thread "main" java.lang.IllegalArgumentException: Multiple entries with same key: com/android/timezonepicker/R$array=com.google.turbine.binder.bound.SourceBoundClass@578486a3 and com/android/timezonepicker/R$array=com.google.turbine.binder.bound.SourceBoundClass@551aa95a
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:186)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:102)
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:88)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:359)
	at com.google.turbine.binder.env.SimpleEnv$Builder.build(SimpleEnv.java:48)
	at com.google.turbine.binder.Binder.bindSourceBoundClasses(Binder.java:124)
	at com.google.turbine.binder.Binder.bind(Binder.java:74)
	at com.google.turbine.main.Main.compile(Main.java:76)
	at com.google.turbine.main.Main.compile(Main.java:61)
	at com.google.turbine.main.Main.main(Main.java:56)
[  0% 8/27094] Target Java: out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/classes-full-debug.jar
FAILED: out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/classes-full-debug.jar 
/bin/bash -c "(rm -f out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/classes-full-debug.jar ) && (rm -rf out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/classes out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/anno ) && (mkdir -p out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/ ) && (mkdir -p out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/classes out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/anno ) && (out/soong/host/linux-x86/bin/zipsync -d out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/srcjars -l out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/srcjar-list -f \"*.java\"  out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/aapt2.srcjar ) && (if [ -s out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/java-source-list -o -s out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/srcjar-list ] ; then out/soong/host/linux-x86/bin/soong_javac_wrapper  prebuilts/jdk/jdk9/linux-x86/bin/javac -Xmaxerrs 9999999 -encoding UTF-8 -sourcepath \"\" -g -XDskipDuplicateBridges=true -XDstringConcat=inline -encoding UTF-8   -bootclasspath out/target/common/obj/JAVA_LIBRARIES/sdk_v15_intermediates/classes-header.jar:out/target/common/obj/JAVA_LIBRARIES/core-lambda-stubs_intermediates/classes-header.jar    -d out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/classes -s out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/anno  -source 1.7 -target 1.7  \\@out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/java-source-list \\@out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/srcjar-list || ( rm -rf out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/classes ; exit 41 ) fi ) && (find out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/classes -name 'R.class' -o -name 'R\$*.class' -o -name 'Manifest.class' -o -name 'Manifest\$*.class' | xargs rm -rf ) && (prebuilts/jdk/jdk9/linux-x86/bin/jar -cf out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/classes-full-debug.jar     @<(find out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/classes -type f | sort | build/soong/scripts/jar-args.sh out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/classes; echo \"-C out/empty .\") )"
out/target/common/obj/JAVA_LIBRARIES/colorpicker_intermediates/srcjars/com/android/colorpicker/R.java:10: error: duplicate class: com.android.colorpicker.R
public final class R {
             ^
1 error
[  0% 9/27094] Target Java: out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/classes-full-debug.jar
FAILED: out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/classes-full-debug.jar 
/bin/bash -c "(rm -f out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/classes-full-debug.jar ) && (rm -rf out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/classes out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/anno ) && (mkdir -p out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/ ) && (mkdir -p out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/classes out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/anno ) && (out/soong/host/linux-x86/bin/zipsync -d out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/srcjars -l out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/srcjar-list -f \"*.java\"  out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/aapt.srcjar ) && (if [ -s out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/java-source-list -o -s out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/srcjar-list ] ; then out/soong/host/linux-x86/bin/soong_javac_wrapper  prebuilts/jdk/jdk9/linux-x86/bin/javac -Xmaxerrs 9999999 -encoding UTF-8 -sourcepath \"\" -g -XDskipDuplicateBridges=true -XDstringConcat=inline -encoding UTF-8   -bootclasspath out/target/common/obj/JAVA_LIBRARIES/sdk_v17_intermediates/classes-header.jar:out/target/common/obj/JAVA_LIBRARIES/core-lambda-stubs_intermediates/classes-header.jar    -d out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/classes -s out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/anno  -source 1.7 -target 1.7  \\@out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/java-source-list \\@out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/srcjar-list || ( rm -rf out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/classes ; exit 41 ) fi ) && (find out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/classes -name 'R.class' -o -name 'R\$*.class' -o -name 'Manifest.class' -o -name 'Manifest\$*.class' | xargs rm -rf ) && (prebuilts/jdk/jdk9/linux-x86/bin/jar -cf out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/classes-full-debug.jar     @<(find out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/classes -type f | sort | build/soong/scripts/jar-args.sh out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/classes; echo \"-C out/empty .\") )"
out/target/common/obj/JAVA_LIBRARIES/android-opt-timezonepicker_intermediates/srcjars/com/android/timezonepicker/R.java:10: error: duplicate class: com.android.timezonepicker.R
public final class R {
             ^
1 error
[  0% 11/27094] Target Java: out/target/common/obj/JAVA_LIBRARIES/xmp_toolkit_intermediates/classes-full-debug.jar
ninja: build stopped: subcommand failed.
16:56:40 ninja failed with: exit status 1

#### failed to build some targets (17 seconds) ####

```

**Comment by ix5** [comment]
Try `make installclean`, and if that doesn't suffice, try removing `out/target/common/obj/JAVA_LIBRARIES`

**Comment by MartinX3** [comment]
What does "make installclean" exactly?
Or where can I read a manual about every AOSP make command?

**Comment by MartinX3** [comment]
@ix5

**Comment by ploth** [comment]
I removed the entire `out` folder and compiled again with `make`. He was basically right with old conflicting files.

**Comment by MartinX3** [comment]
@ploth 
Ahh, it combines `make clean` and `make`

Why not just removing the target folder with the devices in "out"?

**Comment by MarijnS95** [comment]
@MartinX3 `make installclean` removes images and their packaging directories (something along the lines of `rm -rf out/target/product/<device>/{system,vendor,root,boot,data,userdata,recovery,ramdisk}{,.img}`). This is to prevent files from another flavor to end up in the current build, _without_ deleting intermediate build files (it does not combine `make clean` and `make`).
