### ISSUE TITLE
[maple] Can't record video with primary camera

### ISSUE THREAD

**Issue by dimitar10** [sonyxperiadev/bug_tracker#32]
**Platform:** yoshino
**Device:** maple
**Kernel version:** 4.4 (9c6cb35, manually built on 13 Nov)
**Android version:** 8.0.0
**Firmware version:** v05

**Description**
Users can't record video with the primary camera.

**Symptoms**
After the recording of video fails, the users are shown with a `Camera error` alert dialog.

**How to reproduce**
`Camera App -> Video -> Record`

**Logcat**

```
07-12 04:19:27.944 E/MediaRecorder( 2610): start failed: -19
07-12 04:19:27.945 E/CAM_VideoModule( 2610): Could not start media recorder. 
07-12 04:19:27.945 E/CAM_VideoModule( 2610): java.lang.RuntimeException: start failed.
07-12 04:19:27.945 E/CAM_VideoModule( 2610): 	at android.media.MediaRecorder.start(Native Method)
07-12 04:19:27.945 E/CAM_VideoModule( 2610): 	at com.android.camera.VideoModule$11.onStorageUpdateDone(VideoModule.java:1382)
07-12 04:19:27.945 E/CAM_VideoModule( 2610): 	at com.android.camera.CameraActivity$20.onPostExecute(CameraActivity.java:2351)
07-12 04:19:27.945 E/CAM_VideoModule( 2610): 	at com.android.camera.CameraActivity$20.onPostExecute(CameraActivity.java:2345)
07-12 04:19:27.945 E/CAM_VideoModule( 2610): 	at android.os.AsyncTask.finish(AsyncTask.java:695)
07-12 04:19:27.945 E/CAM_VideoModule( 2610): 	at android.os.AsyncTask.-wrap1(Unknown Source:0)
07-12 04:19:27.945 E/CAM_VideoModule( 2610): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
07-12 04:19:27.945 E/CAM_VideoModule( 2610): 	at android.os.Handler.dispatchMessage(Handler.java:105)
07-12 04:19:27.945 E/CAM_VideoModule( 2610): 	at android.os.Looper.loop(Looper.java:164)
07-12 04:19:27.945 E/CAM_VideoModule( 2610): 	at android.app.ActivityThread.main(ActivityThread.java:6541)
07-12 04:19:27.945 E/CAM_VideoModule( 2610): 	at java.lang.reflect.Method.invoke(Native Method)
07-12 04:19:27.945 E/CAM_VideoModule( 2610): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
07-12 04:19:27.945 E/CAM_VideoModule( 2610): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
07-12 04:19:27.945 E/CAM_FatalErrorHandler( 2610): Handling Camera Access Failure:
07-12 04:19:27.945 E/CAM_FatalErrorHandler( 2610): java.lang.Exception
07-12 04:19:27.945 E/CAM_FatalErrorHandler( 2610): 	at com.android.camera.FatalErrorHandlerImpl.onGenericCameraAccessFailure(FatalErrorHandlerImpl.java:84)
07-12 04:19:27.945 E/CAM_FatalErrorHandler( 2610): 	at com.android.camera.VideoModule$11.onStorageUpdateDone(VideoModule.java:1385)
07-12 04:19:27.945 E/CAM_FatalErrorHandler( 2610): 	at com.android.camera.CameraActivity$20.onPostExecute(CameraActivity.java:2351)
07-12 04:19:27.945 E/CAM_FatalErrorHandler( 2610): 	at com.android.camera.CameraActivity$20.onPostExecute(CameraActivity.java:2345)
07-12 04:19:27.945 E/CAM_FatalErrorHandler( 2610): 	at android.os.AsyncTask.finish(AsyncTask.java:695)
07-12 04:19:27.945 E/CAM_FatalErrorHandler( 2610): 	at android.os.AsyncTask.-wrap1(Unknown Source:0)
07-12 04:19:27.945 E/CAM_FatalErrorHandler( 2610): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
07-12 04:19:27.945 E/CAM_FatalErrorHandler( 2610): 	at android.os.Handler.dispatchMessage(Handler.java:105)
07-12 04:19:27.945 E/CAM_FatalErrorHandler( 2610): 	at android.os.Looper.loop(Looper.java:164)
07-12 04:19:27.945 E/CAM_FatalErrorHandler( 2610): 	at android.app.ActivityThread.main(ActivityThread.java:6541)
07-12 04:19:27.945 E/CAM_FatalErrorHandler( 2610): 	at java.lang.reflect.Method.invoke(Native Method)
07-12 04:19:27.945 E/CAM_FatalErrorHandler( 2610): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
07-12 04:19:27.945 E/CAM_FatalErrorHandler( 2610): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
07-12 04:19:27.945 E/CAM_CameraUtil( 2610): Show fatal error dialog
07-12 04:19:27.960 I/CAM_VideoModule( 2610): Releasing media recorder.
07-12 04:19:27.961 V/CAM_VideoModule( 2610): Empty video file deleted: /storage/emulated/0/DCIM/Camera/VID_19700712_041927.mp4.tmp
```

**Comment by kholk** [comment]
This issue should be solved by the PR https://github.com/sonyxperiadev/kernel/pull/1509

Please confirm.

**Comment by jerpelea** [comment]
BUG confirmed for Android 7.1 and Android 8

**Comment by jerpelea** [comment]
keyaki is fine which suggests the the issue is limited to the yoshino platform

**Comment by jerpelea** [comment]
https://github.com/sonyxperiadev/device-sony-yoshino/commit/44043d12c207f4c45e7948f2fe08e59b941c388f#diff-34b8fb38e545fb1f9517403e9372c001
fixed
