### ISSUE TITLE
[suzu] Bluetooth crashes after rebooting when Bluetooth tethering is engaged

### ISSUE THREAD

**Issue by dimitar10** [sonyxperiadev/bug_tracker#35]
**Platform:** loire
**Device:** suzu
**Kernel version:** 4.4 (567bc74, manually built on Nov 13)
**Android version:** 7.1.1
**Firmware version:** v05

**Description**
Bluetooth crashes after rebooting when Bluetooth tethering is engaged. The issue is sporadic and is possibly present on other devices like **kagura** or **maple**.

**Symptoms**
Bluetooth application crashes, after following the steps described bellow. Afterwards, the Bluetooth application might continue to function properly or can crash again.

**How to reproduce**
1. Enable Bluetooth
2. Establish Bluetooth connection with another device
3. Enable Bluetooth tethering from `Wireless & networks -> Tethering & portable hotspot`
4. Setup other device to use internet connection via Bluetooth
5. Reboot device (or reboot both devices)
6. Try to Establish Bluetooth connection again (but don't enable Bluetooth tethering immediately)
7. The connection won't be established right away and the Bluetooth application is likely to crash

**Logcat**

```
11-13 16:36:51.386 D/BluetoothPanServiceJni( 2053): connection_state_callback(L72): state:0, local_role:2, remote_role:1
11-13 16:36:51.389 D/PanService( 2053): handlePanDeviceStateChange preState: 1 state: 2
11-13 16:36:51.390 I/bt_btif_pan( 2053): bta_pan_callback_transfer: event = BTA_PAN_CLOSE_EVT handle 1
11-13 16:36:51.390 D/PanService( 2053): handlePanDeviceStateChange LOCAL_PANU_ROLE:REMOTE_NAP_ROLE state = 2, prevState = 1
11-13 16:36:51.391 D/Bluetooth Tethering( 2053): Registering NetworkFactory
11-13 16:36:51.393 D/PanService( 2053): Pan Device state : device: 00:09:EC:13:C5:12 State:1->2
11-13 16:36:51.393 D/ConnectivityService(  910): Got NetworkFactory Messenger for Bluetooth Tethering
11-13 16:36:51.394 D/BluetoothAdapterService( 2053): getAdapterService() - returning com.android.bluetooth.btservice.AdapterService@3414155
11-13 16:36:51.395 D/BluetoothAdapterService( 2053): handleMessage() - Message: 20
11-13 16:36:51.396 D/BluetoothAdapterService( 2053): handleMessage() - MESSAGE_PROFILE_CONNECTION_STATE_CHANGED
11-13 16:36:51.396 D/CachedBluetoothDevice( 2075): onProfileStateChanged: profile PAN newProfileState 2
11-13 16:36:51.396 D/CachedBluetoothDevice( 2243): onProfileStateChanged: profile PAN newProfileState 2
11-13 16:36:51.397 D/BluetoothAdapterProperties( 2053): CONNECTION_STATE_CHANGE: 00:09:EC:13:C5:12: 1 -> 2
11-13 16:36:51.400 D/Bluetooth Tethering( 2053): got request NetworkRequest [ REQUEST id=1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ] with score 0
11-13 16:36:51.401 D/Bluetooth Tethering( 2053): ipProvisioningThread(+bt-pan): mNetworkInfo=[type: Bluetooth Tethering[], state: UNKNOWN/IDLE, reason: (unspecified), extra: (none), failover: false, available: false, roaming: false, metered: false]
11-13 16:36:51.411 D/BluetoothPanServiceJni( 2053): connection_state_callback(L72): state:2, local_role:2, remote_role:1
11-13 16:36:51.413 D/PanService( 2053): handlePanDeviceStateChange preState: 2 state: 0
11-13 16:36:51.414 D/PanService( 2053): handlePanDeviceStateChange LOCAL_PANU_ROLE:REMOTE_NAP_ROLE state = 0, prevState = 2
11-13 16:36:51.432 E/IpManager.bt-pan( 2053): Failed to disable IPv6java.lang.IllegalStateException: command '47 interface ipv6 bt-pan disable' failed with '400 47 Failed to change IPv6 state (No such file or directory)'
11-13 16:36:51.434 D/CommandListener(  553): Clearing all IP addresses on bt-pan
11-13 16:36:51.438 D/Bluetooth Tethering( 2053): Unregistering NetworkFactory
11-13 16:36:51.438 D/PanService( 2053): Pan Device state : device: 00:09:EC:13:C5:12 State:2->0
11-13 16:36:51.438 D/ConnectivityService(  910): unregisterNetworkFactory for Bluetooth Tethering
11-13 16:36:51.438 D/BluetoothAdapterService( 2053): getAdapterService() - returning com.android.bluetooth.btservice.AdapterService@3414155
11-13 16:36:51.440 D/BluetoothAdapterService( 2053): handleMessage() - Message: 20
11-13 16:36:51.441 D/BluetoothAdapterService( 2053): handleMessage() - MESSAGE_PROFILE_CONNECTION_STATE_CHANGED
11-13 16:36:51.441 D/CachedBluetoothDevice( 2243): onProfileStateChanged: profile PAN newProfileState 0
11-13 16:36:51.441 D/CachedBluetoothDevice( 2075): onProfileStateChanged: profile PAN newProfileState 0
11-13 16:36:51.442 E/IpManager.bt-pan( 2053): Unable to change interface settings: java.lang.IllegalStateException: command '49 interface ipv6privacyextensions bt-pan enable' failed with '400 49 Failed to set ipv6 privacy extensions (No such file or directory)'
11-13 16:36:51.443 D/BluetoothAdapterProperties( 2053): CONNECTION_STATE_CHANGE: 00:09:EC:13:C5:12: 2 -> 0
11-13 16:36:51.446 D/DhcpClient( 2053): doQuit
11-13 16:36:51.450 E/DhcpClient( 2053): Can't determine ifindex or MAC address for bt-pan
11-13 16:36:51.450 E/DhcpClient( 2053): java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.net.NetworkInterface.getHardwareAddress()' on a null object reference
11-13 16:36:51.450 E/DhcpClient( 2053): 	at android.net.dhcp.DhcpClient.initInterface(DhcpClient.java:273)
11-13 16:36:51.450 E/DhcpClient( 2053): 	at android.net.dhcp.DhcpClient.-wrap1(DhcpClient.java)
11-13 16:36:51.450 E/DhcpClient( 2053): 	at android.net.dhcp.DhcpClient$DhcpState.enter(DhcpClient.java:611)
11-13 16:36:51.450 E/DhcpClient( 2053): 	at com.android.internal.util.StateMachine$SmHandler.invokeEnterMethods(StateMachine.java:1021)
11-13 16:36:51.450 E/DhcpClient( 2053): 	at com.android.internal.util.StateMachine$SmHandler.performTransitions(StateMachine.java:867)
11-13 16:36:51.450 E/DhcpClient( 2053): 	at com.android.internal.util.StateMachine$SmHandler.handleMessage(StateMachine.java:809)
11-13 16:36:51.450 E/DhcpClient( 2053): 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-13 16:36:51.450 E/DhcpClient( 2053): 	at android.os.Looper.loop(Looper.java:154)
11-13 16:36:51.450 E/DhcpClient( 2053): 	at android.os.HandlerThread.run(HandlerThread.java:61)
11-13 16:36:51.453 D/DhcpClient( 2053): onQuitting
11-13 16:36:53.251 D/BluetoothPan( 2243): connect(00:09:EC:13:C5:12)
11-13 16:36:53.259 D/BluetoothPanServiceJni( 2053): connectPanNative(L187): in
11-13 16:36:53.260 D/BluetoothPanServiceJni( 2053): connection_state_callback(L72): state:1, local_role:2, remote_role:1
11-13 16:36:53.261 D/CachedBluetoothDevice( 2243): Command sent successfully:CONNECT Address:00:09:EC:13:C5:12 Profile:PAN
11-13 16:36:53.266 I/PanService( 2053): state 1 Num of connected pan devices: 0
11-13 16:36:53.266 D/PanService( 2053): handlePanDeviceStateChange preState: 0 state: 1
11-13 16:36:53.267 D/PanService( 2053): handlePanDeviceStateChange LOCAL_PANU_ROLE:REMOTE_NAP_ROLE state = 1, prevState = 0
11-13 16:36:53.267 D/PanService( 2053): Pan Device state : device: 00:09:EC:13:C5:12 State:0->1
11-13 16:36:53.268 D/BluetoothAdapterService( 2053): getAdapterService() - returning com.android.bluetooth.btservice.AdapterService@3414155
11-13 16:36:53.270 D/BluetoothAdapterService( 2053): handleMessage() - Message: 20
11-13 16:36:53.271 D/CachedBluetoothDevice( 2075): onProfileStateChanged: profile PAN newProfileState 1
11-13 16:36:53.273 D/BluetoothAdapterService( 2053): handleMessage() - MESSAGE_PROFILE_CONNECTION_STATE_CHANGED
11-13 16:36:53.276 D/BluetoothAdapterProperties( 2053): CONNECTION_STATE_CHANGE: 00:09:EC:13:C5:12: 0 -> 1
11-13 16:36:53.279 D/CachedBluetoothDevice( 2243): onProfileStateChanged: profile PAN newProfileState 1
11-13 16:36:53.331 W/bt_btif ( 2053): new conn_srvc id:14, app_id:0
11-13 16:36:53.332 W/bt_btif ( 2053): bta_dm_pm_ssr conn_srvc id:14, app_id:0
11-13 16:36:53.332 W/bt_btif ( 2053): bta_dm_pm_ssr ssr:2, lat:1200
11-13 16:36:53.332 W/bt_btif ( 2053): bta_dm_pm_ssr conn_srvc id:14, app_id:0
11-13 16:36:53.333 W/bt_btif ( 2053): bta_dm_pm_ssr ssr:2, lat:1200
11-13 16:36:53.338 D/BluetoothPanServiceJni( 2053): connection_state_callback(L72): state:0, local_role:2, remote_role:1
11-13 16:36:53.341 D/PanService( 2053): handlePanDeviceStateChange preState: 1 state: 2
11-13 16:36:53.341 D/PanService( 2053): handlePanDeviceStateChange LOCAL_PANU_ROLE:REMOTE_NAP_ROLE state = 2, prevState = 1
11-13 16:36:53.342 D/Bluetooth Tethering( 2053): Registering NetworkFactory
11-13 16:36:53.344 E/bt_pan  ( 2053): PAN is not active Data write failed
11-13 16:36:53.344 I/bt_btif_pan( 2053): bta_pan_callback_transfer: event = BTA_PAN_CLOSE_EVT handle 1
11-13 16:36:53.344 E/bt_pan  ( 2053): PAN is not active Data write failed
11-13 16:36:53.345 D/ConnectivityService(  910): Got NetworkFactory Messenger for Bluetooth Tethering
11-13 16:36:53.345 D/PanService( 2053): Pan Device state : device: 00:09:EC:13:C5:12 State:1->2
11-13 16:36:53.346 D/BluetoothAdapterService( 2053): getAdapterService() - returning com.android.bluetooth.btservice.AdapterService@3414155
11-13 16:36:53.349 D/CachedBluetoothDevice( 2243): onProfileStateChanged: profile PAN newProfileState 2
11-13 16:36:53.351 D/BluetoothAdapterService( 2053): handleMessage() - Message: 20
11-13 16:36:53.355 D/Bluetooth Tethering( 2053): ipProvisioningThread(+bt-pan): mNetworkInfo=[type: Bluetooth Tethering[], state: DISCONNECTED/DISCONNECTED, reason: (unspecified), extra: (none), failover: false, available: false, roaming: false, metered: false]
11-13 16:36:53.359 D/BluetoothAdapterService( 2053): handleMessage() - MESSAGE_PROFILE_CONNECTION_STATE_CHANGED
11-13 16:36:53.361 D/NetlinkEvent(  553): Unknown ifindex 16 in RTM_DELADDR
11-13 16:36:53.363 D/CachedBluetoothDevice( 2075): onProfileStateChanged: profile PAN newProfileState 2
11-13 16:36:53.368 D/BluetoothAdapterProperties( 2053): CONNECTION_STATE_CHANGE: 00:09:EC:13:C5:12: 1 -> 2
11-13 16:36:53.373 D/BluetoothPanServiceJni( 2053): connection_state_callback(L72): state:2, local_role:2, remote_role:1
--------- beginning of crash
11-13 16:36:53.376 E/AndroidRuntime( 2053): FATAL EXCEPTION: IpManager.bt-pan
11-13 16:36:53.376 E/AndroidRuntime( 2053): Process: com.android.bluetooth, PID: 2053
11-13 16:36:53.376 E/AndroidRuntime( 2053): java.lang.RuntimeException: StateMachine.handleMessage: The start method not called, received msg: { when=-9ms what=5 target=com.android.internal.util.StateMachine$SmHandler }
11-13 16:36:53.376 E/AndroidRuntime( 2053): 	at com.android.internal.util.StateMachine$SmHandler.handleMessage(StateMachine.java:806)
11-13 16:36:53.376 E/AndroidRuntime( 2053): 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-13 16:36:53.376 E/AndroidRuntime( 2053): 	at android.os.Looper.loop(Looper.java:154)
11-13 16:36:53.376 E/AndroidRuntime( 2053): 	at android.os.HandlerThread.run(HandlerThread.java:61)
11-13 16:36:53.377 D/PanService( 2053): handlePanDeviceStateChange preState: 2 state: 0
11-13 16:36:53.378 D/PanService( 2053): handlePanDeviceStateChange LOCAL_PANU_ROLE:REMOTE_NAP_ROLE state = 0, prevState = 2
11-13 16:36:53.381 D/Bluetooth Tethering( 2053): Unregistering NetworkFactory
11-13 16:36:53.381 D/ConnectivityService(  910): unregisterNetworkFactory for Bluetooth Tethering
11-13 16:36:53.382 D/PanService( 2053): Pan Device state : device: 00:09:EC:13:C5:12 State:2->0
11-13 16:36:53.382 D/BluetoothAdapterService( 2053): getAdapterService() - returning com.android.bluetooth.btservice.AdapterService@3414155
11-13 16:36:53.386 D/CachedBluetoothDevice( 2243): onProfileStateChanged: profile PAN newProfileState 0
11-13 16:36:53.389 D/BluetoothAdapterService( 2053): handleMessage() - Message: 20
11-13 16:36:53.396 D/BluetoothAdapterService( 2053): handleMessage() - MESSAGE_PROFILE_CONNECTION_STATE_CHANGED
11-13 16:36:53.404 D/CachedBluetoothDevice( 2075): onProfileStateChanged: profile PAN newProfileState 0
11-13 16:36:53.412 D/BluetoothAdapterProperties( 2053): CONNECTION_STATE_CHANGE: 00:09:EC:13:C5:12: 2 -> 0
11-13 16:36:53.476 I/Adreno  (  910): QUALCOMM build                   : 49a2ab3, Ifedc5bd8d0
11-13 16:36:53.476 I/Adreno  (  910): Build Date                       : 12/15/16
11-13 16:36:53.476 I/Adreno  (  910): OpenGL ES Shader Compiler Version: XE031.09.00.04
11-13 16:36:53.476 I/Adreno  (  910): Local Branch                     : 
11-13 16:36:53.476 I/Adreno  (  910): Remote Branch                    : 
11-13 16:36:53.476 I/Adreno  (  910): Remote Branch                    : 
11-13 16:36:53.476 I/Adreno  (  910): Reconstruct Branch               : 
11-13 16:36:53.486 I/OpenGLRenderer(  910): Initialized EGL, version 1.4
11-13 16:36:53.486 D/OpenGLRenderer(  910): Swap behavior 1
11-13 16:36:54.994 I/MSM-irqbalance(  509): Decided to move IRQ3 from CPU4 [P:0] to CPU0 [P:1] (banned)
11-13 16:36:54.995 I/MSM-irqbalance(  509): Decided to move IRQ5 from CPU4 [P:0] to CPU3 [P:1] (banned)
11-13 16:36:56.447 D/audio_hw_primary(  541): disable_audio_route: usecase(1) reset and update mixer path: low-latency-playback
11-13 16:36:56.450 D/hardware_info(  541): hw_info_append_hw_type : device_name = speaker
11-13 16:36:56.450 D/audio_hw_primary(  541): disable_snd_device: snd_device(2: speaker)
11-13 16:36:57.470 I/bt_btm_sec( 2053): btm_sec_disconnected clearing pending flag handle:12 reason:22
11-13 16:36:57.473 E/BluetoothRemoteDevices( 2053): state12newState1

```

**Comment by kholk** [comment]
Please (anyone) try to reproduce the issue on Tone and Yoshino: this will make sure that the problem is experienced globally.

Depending on that, the research paths will differ a lot.
Thanks

**Comment by jerpelea** [comment]
the bug can not be reproduced on suzu as host with a maple as guest
