### ISSUE TITLE
AOSP Gallery app cannot play trimmed video

### ISSUE THREAD

**Issue by AdFad666** [sonyxperiadev/bug_tracker#45]
**Platform:** Yoshino
**Device:** Poplar
**Kernel version:** 4.4 
**Android version:** 8.0

**Description**
After recording a long video it is desirable to trim it to a suitable length. This can be done in the Gallery app. 

**Symptoms**
Trimmed videos produced by the Gallery app cannot be played by the Gallery app. The videos are however valid as they can be played in VLC on a PC.
 
**How to reproduce**
* Record a long video.
* Open the Gallery app.
* Choose the recorded video.
* Select TRIM from the options.
* Save the trimmed video.
* Try to view the trimmed video.

**Comment by AdFad666** [comment]
```
11-19 03:48:57.481   584  2341 D audio_hw_primary: enable_snd_device: snd_device(2: speaker)
11-19 03:48:57.522   584  2341 D audio_hw_primary: enable_audio_route: usecase(1) apply and update mixer path: low-latency-playback
11-19 03:48:57.556   884   944 I ActivityManager: Killing 2112:com.android.managedprovisioning/u0a16 (adj 906): empty #17
11-19 03:48:57.588   584  2341 E rqbalance_ctl: Cannot connect to PowerServer socket
11-19 03:48:57.608   676   730 D MediaBufferGroup: creating MemoryDealer
11-19 03:48:57.653  2713  2797 I MPEG4Writer: limits: 4294967295/0 bytes/us, bit rate: -1 bps and the estimated moov size 3195 bytes
11-19 03:48:57.670  2713  2801 I MPEG4Writer: setStartTimestampUs: 1024000
11-19 03:48:57.670  2713  2801 I MPEG4Writer: Earliest track starting time: 1024000
11-19 03:48:57.697  2713  2800 I MPEG4Writer: setStartTimestampUs: 1514088
11-19 03:48:57.716  2713  2797 D VideoUtils: The current sample is over the trim end time.
11-19 03:48:57.717  2713  2800 I MPEG4Writer: Received total/0-length (11/0) buffers and encoded 11 frames. - Video
11-19 03:48:57.717  2713  2797 D MPEG4Writer: Video track stopping. Stop source
11-19 03:48:57.717  2713  2797 D MPEG4Writer: Video track source stopping
11-19 03:48:57.717  2713  2797 D MPEG4Writer: Video track source stopped
11-19 03:48:57.717  2713  2797 D MPEG4Writer: Video track stopped. Stop source
11-19 03:48:57.717  2713  2797 D MPEG4Writer: Audio track stopping. Stop source
11-19 03:48:57.717  2713  2797 D MPEG4Writer: Audio track source stopping
11-19 03:48:57.717  2713  2797 D MPEG4Writer: Audio track source stopped
11-19 03:48:57.720  2713  2801 I MPEG4Writer: Received total/0-length (45/0) buffers and encoded 45 frames. - Audio
11-19 03:48:57.721  2713  2801 I MPEG4Writer: Audio track drift time: 0 us
11-19 03:48:57.722  2713  2797 D MPEG4Writer: Audio track stopped. Stop source
11-19 03:48:57.722  2713  2797 D MPEG4Writer: Duration from tracks range is [465912, 959999] us
11-19 03:48:57.722  2713  2797 D MPEG4Writer: Stopping writer thread
11-19 03:48:57.722  2713  2799 D MPEG4Writer: 0 chunks are written in the last batch
11-19 03:48:57.723  2713  2797 D MPEG4Writer: Writer thread stopped
11-19 03:48:57.724  2713  2797 D MPEG4Writer: Video track stopping. Stop source
11-19 03:48:57.724  2713  2797 D MPEG4Writer: Audio track stopping. Stop source
11-19 03:48:57.831  2713  2713 D AndroidRuntime: Shutting down VM
11-19 03:48:57.833  2713  2713 E AndroidRuntime: FATAL EXCEPTION: main
11-19 03:48:57.833  2713  2713 E AndroidRuntime: Process: com.android.gallery3d, PID: 2713
11-19 03:48:57.833  2713  2713 E AndroidRuntime: android.os.FileUriExposedException: file:///storage/emulated/0/DCIM/Camera/TRIM_20171119_034857.mp4 exposed beyond app through Intent.getData()
11-19 03:48:57.833  2713  2713 E AndroidRuntime: 	at android.os.StrictMode.onFileUriExposed(StrictMode.java:1958)
11-19 03:48:57.833  2713  2713 E AndroidRuntime: 	at android.net.Uri.checkFileUriExposed(Uri.java:2348)
11-19 03:48:57.833  2713  2713 E AndroidRuntime: 	at android.content.Intent.prepareToLeaveProcess(Intent.java:9766)
11-19 03:48:57.833  2713  2713 E AndroidRuntime: 	at android.content.Intent.prepareToLeaveProcess(Intent.java:9720)
11-19 03:48:57.833  2713  2713 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1609)
11-19 03:48:57.833  2713  2713 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4472)
11-19 03:48:57.833  2713  2713 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4430)
11-19 03:48:57.833  2713  2713 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:4791)
11-19 03:48:57.833  2713  2713 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:4759)
11-19 03:48:57.833  2713  2713 E AndroidRuntime: 	at com.android.gallery3d.app.TrimVideo$3$1.run(TrimVideo.java:266)
11-19 03:48:57.833  2713  2713 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
11-19 03:48:57.833  2713  2713 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
11-19 03:48:57.833  2713  2713 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
11-19 03:48:57.833  2713  2713 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6544)
11-19 03:48:57.833  2713  2713 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-19 03:48:57.833  2713  2713 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
11-19 03:48:57.833  2713  2713 E AndroidRuntime: 	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
11-19 03:48:57.833  2713  2713 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
11-19 03:48:57.833  2713  2713 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:284)
11-19 03:48:57.835  2713  2713 E AndroidRuntime: Error reporting crash
11-19 03:48:57.835  2713  2713 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
11-19 03:48:57.835  2713  2713 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
11-19 03:48:57.835  2713  2713 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:748)
11-19 03:48:57.835  2713  2713 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.handleApplicationCrash(IActivityManager.java:4321)
11-19 03:48:57.835  2713  2713 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:115)
11-19 03:48:57.835  2713  2713 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
11-19 03:48:57.835  2713  2713 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
11-19 03:48:57.835  2713  2713 E AndroidRuntime: 	at java.lang.Thread.dispatchUncaughtException(Thread.java:1953)
11-19 03:48:57.835  2713  2713 I Process : Sending signal. PID: 2713 SIG: 9
11-19 03:48:57.867   884   944 I WindowManager: WIN DEATH: Window{f7a9231 u0 Trimming EXITING}
11-19 03:48:57.867   884  1548 I MediaFocusControl: AudioFocus  removeFocusStackEntryOnDeath(): removing entry for android.os.BinderProxy@2ce34a2
11-19 03:48:57.869   884   938 I ActivityManager: Process com.android.gallery3d (pid 2713) has died: fore TOP 
11-19 03:48:57.870   884   938 W ActivityManager: Force removing ActivityRecord{b205f89 u0 com.android.gallery3d/.app.TrimVideo t18}: app died, no saved state
11-19 03:48:57.870   884  1140 W InputDispatcher: channel '9cf97cb com.android.gallery3d/com.android.gallery3d.app.TrimVideo (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
11-19 03:48:57.871   884  1140 E InputDispatcher: channel '9cf97cb com.android.gallery3d/com.android.gallery3d.app.TrimVideo (server)' ~ Channel is unrecoverably broken and will be disposed!
11-19 03:48:57.871   884  1140 W InputDispatcher: channel '9ef41c9 com.android.gallery3d/com.android.gallery3d.app.GalleryActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
11-19 03:48:57.871   884  1140 E InputDispatcher: channel '9ef41c9 com.android.gallery3d/com.android.gallery3d.app.GalleryActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
11-19 03:48:57.871   884  1738 I WindowManager: WIN DEATH: Window{9cf97cb u0 com.android.gallery3d/com.android.gallery3d.app.TrimVideo}
11-19 03:48:57.871   884  1738 W InputDispatcher: Attempted to unregister already unregistered input channel '9cf97cb com.android.gallery3d/com.android.gallery3d.app.TrimVideo (server)'
11-19 03:48:57.871   615   659 E SurfaceFlinger: removeLayer called with a layer whose parent has been removed
11-19 03:48:57.872   615   659 E SurfaceFlinger: removeLayer called with a layer whose parent has been removed
11-19 03:48:57.872   681  1403 D NuPlayerDriver: reset(0xe880d780) at state 6
11-19 03:48:57.874   681  1403 D NuPlayerDriver: notifyListener_l(0xe880d780), (8, 0, 0, -1), loop setting(0, 0)
11-19 03:48:57.877   884  1532 I WindowManager: WIN DEATH: Window{9ef41c9 u0 com.android.gallery3d/com.android.gallery3d.app.GalleryActivity}
11-19 03:48:57.877   884  1532 W InputDispatcher: Attempted to unregister already unregistered input channel '9ef41c9 com.android.gallery3d/com.android.gallery3d.app.GalleryActivity (server)'
11-19 03:48:57.906   884   938 I ActivityManager: Start proc 2803:com.android.gallery3d/u0a47 for activity com.android.gallery3d/.app.GalleryActivity
11-19 03:48:57.907   615  1547 E BufferQueueProducer: [SurfaceView - com.android.gallery3d/com.android.gallery3d.app.TrimVideo#0] cancelBuffer: BufferQueue has been abandoned
11-19 03:48:57.908   615  1547 E BufferQueueProducer: [SurfaceView - com.android.gallery3d/com.android.gallery3d.app.TrimVideo#0] cancelBuffer: BufferQueue has been abandoned
11-19 03:48:57.908   615   656 E BufferQueueProducer: [SurfaceView - com.android.gallery3d/com.android.gallery3d.app.TrimVideo#0] cancelBuffer: BufferQueue has been abandoned
11-19 03:48:57.909   615  1547 E BufferQueueProducer: [SurfaceView - com.android.gallery3d/com.android.gallery3d.app.TrimVideo#0] cancelBuffer: BufferQueue has been abandoned
11-19 03:48:57.911   615  1547 I chatty  : uid=1000(system) Binder:615_4 identical 1 line
11-19 03:48:57.912   615  1547 E BufferQueueProducer: [SurfaceView - com.android.gallery3d/com.android.gallery3d.app.TrimVideo#0] cancelBuffer: BufferQueue has been abandoned
11-19 03:48:57.917   685  2791 I OMX-VDEC-1080P: omx_vdec::component_deinit() complete
11-19 03:48:57.920   685  2791 I OMX-VDEC-1080P: Exit OMX vdec Destructor: fd=6
11-19 03:48:57.920   685  2791 E rqbalance_ctl: Cannot connect to PowerServer socket
11-19 03:48:57.920   685  2791 I OMX-VDEC-1080P: Video slvp perflock released
11-19 03:48:57.921   681  2782 D SurfaceUtils: disconnecting from surface 0xe8678808, reason disconnectFromSurface
11-19 03:48:57.925   681  2781 D SurfaceUtils: connecting to surface 0xe8678808, reason onShutdown
11-19 03:48:57.925   615  1547 E BufferQueueProducer: [SurfaceView - com.android.gallery3d/com.android.gallery3d.app.TrimVideo#0] connect: BufferQueue has been abandoned
11-19 03:48:57.925   681  2781 E SurfaceUtils: Failed to connect to surface 0xe8678808, err -19
11-19 03:48:57.925   681  2781 W NuPlayerDecoder: [OMX.qcom.video.decoder.avc] failed to connect to native window, error=-19
11-19 03:48:57.928   681  2778 D NuPlayerDriver: notifyResetComplete(0xe880d780)
11-19 03:48:57.929   681  1403 D SurfaceUtils: disconnecting from surface 0xe87df808, reason disconnectNativeWindow
11-19 03:48:58.065   884  1049 W ActivityManager: setHasOverlayUi called on unknown pid: 2713
11-19 03:48:58.439  2803  2803 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 10047 <<<<<<
11-19 03:48:58.443  2803  2803 E cutils-trace: Error opening trace file: No such file or directory (2)
11-19 03:48:58.604  2803  2803 D AndroidRuntime: Calling main entry com.android.internal.os.ExecInit
11-19 03:48:58.605  2803  2803 D Zygote  : begin preload
11-19 03:48:58.618  2803  2803 D ExecInitTiming: PreloadResources took to complete: 11ms
11-19 03:48:58.619  2803  2803 I Zygote  : Preloading shared libraries...
11-19 03:48:58.762  2803  2803 D Zygote  : end preload
```

**Comment by oshmoun** [comment]
This should help
https://stackoverflow.com/questions/38200282/android-os-fileuriexposedexception-file-storage-emulated-0-test-txt-exposed
Although, might be worth checking aosp gerrit beforehand,maybe it's already patched on master

**Comment by jerpelea** [comment]
this is an Aosp bug
