### ISSUE TITLE
[Yoshino] [Maple_DSDS] [4.9] [9.0] [v9] Sensor doesnt work well

### ISSUE THREAD

**Issue by kgvarunkanth** [sonyxperiadev/bug_tracker#532]
**Platform:** 
**Device:** 
**Kernel version:** 
**Android version:** 
**Software binaries version:** 

**Description**
Gyrosensor detects sensor value wrong

**Symptoms**
I kept the phone on floor but the gyro sensor data shows me as the phone is moving towards the left side

**Comment by ix5** [comment]
Have you tried using a calibration app?

**Comment by kgvarunkanth** [comment]
> Have you tried using a calibration app?

Yes tried...
But no change....it still has those ....

**Comment by stefanhh0** [comment]
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.14.189-24379-g205a380bd16a¹
**Android version:** android-10.0.0_r40
**Software binaries version:** SW_binaries_for_Xperia_Android_10.0.7.1_r1_v9c_yoshino.img
**Version baseband:** 1307-7511_47.2.A.11.228
**Build:** aosp_g8441-userdebug 10 QQ3A.200705.002 eng.stefan.20200728.091037²

I can confirm the behaviour for my lilac device. I never payed attention to it, but the problem exists since a long time. Since I saw this bug while searching for candidates to be closed I thought it would be a good idea to update the issue.

The app I am using is GPS Status. I did both "Calibrate pitch and fall" and "Compass calibration". After doing so the gyro is still rotating towards the left side as described.

Here a log from a calibration session including both kernel and default logcat output interleaved:
[logcat.log](https://github.com/sonyxperiadev/bug_tracker/files/4993924/logcat.log)

It shows a lot of exceptions:
```
07-29 11:23:33.494  1114  2361 E DatabaseUtils: Writing exception to parcel
07-29 11:23:33.494  1114  2361 E DatabaseUtils: java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_DEVICE_CONFIG
07-29 11:23:33.494  1114  2361 E DatabaseUtils: 	at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2017)
07-29 11:23:33.494  1114  2361 E DatabaseUtils: 	at com.android.providers.settings.SettingsProvider.mutateConfigSetting(SettingsProvider.java:1108)
07-29 11:23:33.494  1114  2361 E DatabaseUtils: 	at com.android.providers.settings.SettingsProvider.insertConfigSetting(SettingsProvider.java:1086)
07-29 11:23:33.494  1114  2361 E DatabaseUtils: 	at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:420)
07-29 11:23:33.494  1114  2361 E DatabaseUtils: 	at android.content.ContentProvider.call(ContentProvider.java:2152)
07-29 11:23:33.494  1114  2361 E DatabaseUtils: 	at android.content.ContentProvider$Transport.call(ContentProvider.java:477)
07-29 11:23:33.494  1114  2361 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:277)
07-29 11:23:33.494  1114  2361 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1021)
07-29 11:23:33.494  1114  2361 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:994)
07-29 11:23:33.501  1114  1186 E KernelWakelockReader: Failed to parse proc line: IPA_RM14
07-29 11:23:33.503  1114  1186 E KernelWakelockReader: Failed to parse proc line: IPA_RM12
```
And:

```
07-29 11:23:36.362  1998  9117 W aolj    : updateFromConfigurations failed with SecurityException [CONTEXT service_id=204 ]
07-29 11:23:36.362  1998  9117 W aolj    : java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_DEVICE_CONFIG
07-29 11:23:36.362  1998  9117 W aolj    : 	at android.os.Parcel.createException(Parcel.java:2071)
07-29 11:23:36.362  1998  9117 W aolj    : 	at android.os.Parcel.readException(Parcel.java:2039)
07-29 11:23:36.362  1998  9117 W aolj    : 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
07-29 11:23:36.362  1998  9117 W aolj    : 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
07-29 11:23:36.362  1998  9117 W aolj    : 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:658)
07-29 11:23:36.362  1998  9117 W aolj    : 	at android.provider.Settings$NameValueCache.putStringForUser(Settings.java:2311)
07-29 11:23:36.362  1998  9117 W aolj    : 	at android.provider.Settings$Config.putString(Settings.java:15087)
07-29 11:23:36.362  1998  9117 W aolj    : 	at android.provider.DeviceConfig.setProperty(DeviceConfig.java:538)
07-29 11:23:36.362  1998  9117 W aolj    : 	at aolh.a(:com.google.android.gms@202614038@20.26.14 (120406-320008519):2)
07-29 11:23:36.362  1998  9117 W aolj    : 	at aolj.a(:com.google.android.gms@202614038@20.26.14 (120406-320008519):25)
07-29 11:23:36.362  1998  9117 W aolj    : 	at aolj.b(:com.google.android.gms@202614038@20.26.14 (120406-320008519):6)
07-29 11:23:36.362  1998  9117 W aolj    : 	at aolj.a(:com.google.android.gms@202614038@20.26.14 (120406-320008519):54)
07-29 11:23:36.362  1998  9117 W aolj    : 	at aolj.f(:com.google.android.gms@202614038@20.26.14 (120406-320008519):4)
07-29 11:23:36.362  1998  9117 W aolj    : 	at aolj.c(:com.google.android.gms@202614038@20.26.14 (120406-320008519):18)
07-29 11:23:36.362  1998  9117 W aolj    : 	at com.google.android.gms.platformconfigurator.PhenotypeConfigurationUpdateListener.a(:com.google.android.gms@202614038@20.26.14 (120406-320008519):17)
07-29 11:23:36.362  1998  9117 W aolj    : 	at com.google.android.gms.platformconfigurator.PhenotypeConfigurationUpdateListener.onHandleIntent(:com.google.android.gms@202614038@20.26.14 (120406-320008519):5)
07-29 11:23:36.362  1998  9117 W aolj    : 	at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@202614038@20.26.14 (120406-320008519):2)
07-29 11:23:36.362  1998  9117 W aolj    : 	at qga.onHandleIntent(:com.google.android.gms@202614038@20.26.14 (120406-320008519):4)
07-29 11:23:36.362  1998  9117 W aolj    : 	at cuo.run(:com.google.android.gms@202614038@20.26.14 (120406-320008519):5)
07-29 11:23:36.362  1998  9117 W aolj    : 	at cun.run(:com.google.android.gms@202614038@20.26.14 (120406-320008519):10)
07-29 11:23:36.362  1998  9117 W aolj    : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-29 11:23:36.362  1998  9117 W aolj    : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-29 11:23:36.362  1998  9117 W aolj    : 	at java.lang.Thread.run(Thread.java:919)
07-29 11:23:36.363  1998  9117 I PhenotypeConfigurationU: Failed to propagate package com.google.android.platform.telephony, retryCount 2 [CONTEXT service_id=204 ]
07-29 11:23:36.369  1998  9117 I aolj    : updateFromConfigurations DeviceConfig for namespace permissions [CONTEXT service_id=204 ]
07-29 11:23:36.370  1114  2361 E DatabaseUtils: Writing exception to parcel
07-29 11:23:36.370  1114  2361 E DatabaseUtils: java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_DEVICE_CONFIG
07-29 11:23:36.370  1114  2361 E DatabaseUtils: 	at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2017)
07-29 11:23:36.370  1114  2361 E DatabaseUtils: 	at com.android.providers.settings.SettingsProvider.mutateConfigSetting(SettingsProvider.java:1108)
07-29 11:23:36.370  1114  2361 E DatabaseUtils: 	at com.android.providers.settings.SettingsProvider.insertConfigSetting(SettingsProvider.java:1086)
07-29 11:23:36.370  1114  2361 E DatabaseUtils: 	at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:420)
07-29 11:23:36.370  1114  2361 E DatabaseUtils: 	at android.content.ContentProvider.call(ContentProvider.java:2152)
07-29 11:23:36.370  1114  2361 E DatabaseUtils: 	at android.content.ContentProvider$Transport.call(ContentProvider.java:477)
07-29 11:23:36.370  1114  2361 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:277)
07-29 11:23:36.370  1114  2361 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1021)
07-29 11:23:36.370  1114  2361 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:994)
``` 
---
¹) The kernel commit can't be found on github:
- Base commit is: https://github.com/sonyxperiadev/kernel/commit/09c26b6a5ff5
- Included PRs: 2326

²) SELinux: enforcing

**Comment by stefanhh0** [comment]
The exceptions seem not to be problem though, see as well: https://gitlab.opengapps.org/opengapps/all/-/issues/3

**Comment by MarijnS95** [comment]
This is all pretty unfortunate, the exact same issue on 4.9 v9 blobs as well as 4.14 means we're either dealing with a longstanding issue or failing hardware (though that's what a calibration is supposed to correct for).

You can safely ignore `java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_DEVICE_CONFIG`, that's just messed up app configurations and AOSP stuff.

@stefanhh0 We tried resetting the sensor calibration on your Yoshino before, do you recall if I pasted the script in one of the other sensor issue topics. It's pretty much as simple as 
```sh
rm /persist/sensors
mkdir -p /persist/sensors/registry/registry
restorecon -R /persist/sensors/registry/registry
chown system:system -R /persist/sensors/registry/registry
```
And then reboot, but be sure to confirm with the script because I may have misremembered the paths...

**Comment by stefanhh0** [comment]
Very good reminder @MarijnS95. One of the steps solved the problem:

I did following, using an updated kernel that includes the PRs for 4.14.190 and CAF Tag: LA.UM.7.1.r1-16600-sm8150.0:

```
rm -r /persist/sensors
mkdir -p /persist/sensors/registry/registry
echo 1 >/persist/sensors/sensors_settings
restorecon -R /persist/sensors
chown system:system -R /persist/sensors
reboot system
```

After reboot I choose to to reset the calibration via the "GPS Status" app, after doing so the gyro remains stable!

@jerpelea this issue can be closed.

**Comment by MarijnS95** [comment]
I don't fully remember, but `echo 1 >/persist/sensors/sensors_settings` might be preventing the HAL from generating a new configuration? I have to check verbose debug logs again to confirm, but one of these files triggers a fresh firmware deployment 🙂

**Comment by stefanhh0** [comment]
Last time when I didn't restore the `/persist/sensors/sensors_settings` android refused to startup sensors at all. At least `/persist/sensors/sns.reg` has been recreated after the reboot. Not sure where it comes from...

**Comment by MarijnS95** [comment]
https://github.com/MarijnS95/device-sony-sepolicy/commit/2a13ac8606c35e0fc7072ad24bc00febe755b0a8 There might be more weirdness like this :grin: 

Just in case, would you mind not restoring anything besides the folders and giving a log? That way we can set up proper policies.

**Comment by stefanhh0** [comment]
Sure, no problem,

cherry picked: https://github.com/MarijnS95/device-sony-sepolicy/commit/2a13ac8606c35e0fc7072ad24bc00febe755b0a8

This time did following:
```
rm -r /persist/sensors
mkdir -p /persist/sensors/registry/registry
restorecon -R /persist/sensors
chown system:system -R /persist/sensors
reboot system
```

[kernel.log](https://github.com/sonyxperiadev/bug_tracker/files/4998887/kernel.log)
```
stefan@mars:~/android/pluto/lilac-bugs$ grep -i sensor kernel.log 
03-02 22:33:52.922     0     0 I init    : Parsing file /vendor/etc/init/android.hardware.sensors@1.0-service.rc...
03-02 22:33:52.936     0     0 I init    : Parsing file /vendor/etc/init/sensors.rc...
03-02 22:33:55.713     0     0 I init    : processing action (post-fs-data) from (/vendor/etc/init/sensors.rc:1)
03-02 22:33:55.810     0     0 I init    : starting service 'vendor.sensors-hal-1-0'...
03-02 22:33:56.591     0     0 I init    : processing action (vendor.qcom.slpiup=1) from (/vendor/etc/init/sensors.rc:29)
03-02 22:33:56.591     0     0 I init    : Command 'enable vendor.sensorspd' action=vendor.qcom.slpiup=1 (/vendor/etc/init/sensors.rc:30) took 0ms and failed: Could not find service
03-02 22:33:56.593     0     0 I init    : starting service 'vendor.sensors'...
```

**Comment by stefanhh0** [comment]
Now the gyro is constantly rotating again. Maybe I just had a lucky boot...
Resetting pitch and fall and recalibrating didn't stop it.

**Comment by stefanhh0** [comment]
After reboot the calibration is always gone, and I need to recalibrate, is that expected?

**Comment by jerpelea** [comment]
the issue has been fixed
