### ISSUE TITLE
[Yoshino][Lilac] Android 10 Linux 4.9 Unable to acquire GateKeeperService

### ISSUE THREAD

**Issue by stefanhh0** [sonyxperiadev/bug_tracker#557]
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.9.215
**Kernel compiler:** gcc
**Android version:** android-10.0.0_r26
**Software binaries version:** SW_binaries_for_Xperia_Android_9.0_2.3.2_v9_yoshino.img
**Version baseband:** 1307-7511_47.2.A.11.228
**Build:** aosp_g8441-userdebug 10 QQ1A.200205.002 eng.stefan.20200308.073852

**Previously working on**
Build from 2020.02.29:
**Kernel version:** 4.9.215
**Build:** aosp_g8441-userdebug 10 QQ1A.200205.002 eng.stefan.20200229.093253

**Description**
Registering a display PIN is no longer possible. Most likely due to GateKeeperService is not available.
 
**Symptoms**
Trying to register a display PIN shows an error message box, after that the display PIN has not been set. 

**How to reproduce**
Reproducible every time building pure AOSP without opengapps (commented out) using https://github.com/stefanhh0/aosp-10/blob/master/build-4.9.sh
Please be aware that I have changed to use the q-mr1-legacy branches for common and sepolicy

**Additional context**
[logcat.txt](https://github.com/sonyxperiadev/bug_tracker/files/4303040/logcat.txt)
```
03-08 09:25:08.495  1225  1225 I LockSettingsService: Reporting device setup complete to IGateKeeperService
03-08 09:25:08.495  1225  1225 E LockSettingsService: Unable to acquire GateKeeperService
03-08 09:25:08.498  1225  1225 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
03-08 09:25:08.498  1225  1225 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'void android.service.gatekeeper.IGateKeeperService.reportDeviceSetupComplete()' on a null object reference
03-08 09:25:08.498  1225  1225 E AndroidRuntime: 	at com.android.server.locksettings.LockSettingsService$DeviceProvisionedObserver.reportDeviceSetupComplete(LockSettingsService.java:3089)
03-08 09:25:08.498  1225  1225 E AndroidRuntime: 	at com.android.server.locksettings.LockSettingsService$DeviceProvisionedObserver.onChange(LockSettingsService.java:3064)
03-08 09:25:08.498  1225  1225 E AndroidRuntime: 	at android.database.ContentObserver.dispatchChange(ContentObserver.java:198)
03-08 09:25:08.498  1225  1225 E AndroidRuntime: 	at android.database.ContentObserver.access$000(ContentObserver.java:28)
03-08 09:25:08.498  1225  1225 E AndroidRuntime: 	at android.database.ContentObserver$Transport.onChange(ContentObserver.java:233)
03-08 09:25:08.498  1225  1225 E AndroidRuntime: 	at com.android.server.content.ContentService.notifyChange(ContentService.java:436)
03-08 09:25:08.498  1225  1225 E AndroidRuntime: 	at android.content.ContentResolver.notifyChange(ContentResolver.java:2387)
03-08 09:25:08.498  1225  1225 E AndroidRuntime: 	at com.android.providers.settings.SettingsProvider$SettingsRegistry$MyHandler.handleMessage(SettingsProvider.java:3224)
03-08 09:25:08.498  1225  1225 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
03-08 09:25:08.498  1225  1225 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
03-08 09:25:08.498  1225  1225 E AndroidRuntime: 	at com.android.server.SystemServer.run(SystemServer.java:542)
03-08 09:25:08.498  1225  1225 E AndroidRuntime: 	at com.android.server.SystemServer.main(SystemServer.java:350)
03-08 09:25:08.498  1225  1225 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-08 09:25:08.498  1225  1225 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
03-08 09:25:08.498  1225  1225 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:908)
[...]
03-08 09:25:57.608  5703  6004 E LockPatternUtils: Unable to save lock password
03-08 09:25:57.608  5703  6004 E LockPatternUtils: java.lang.NullPointerException: Attempt to invoke interface method 'void android.service.gatekeeper.IGateKeeperService.clearSecureUserId(int)' on a null object reference
03-08 09:25:57.608  5703  6004 E LockPatternUtils: 	at android.os.Parcel.createException(Parcel.java:2077)
03-08 09:25:57.608  5703  6004 E LockPatternUtils: 	at android.os.Parcel.readException(Parcel.java:2039)
03-08 09:25:57.608  5703  6004 E LockPatternUtils: 	at android.os.Parcel.readException(Parcel.java:1987)
03-08 09:25:57.608  5703  6004 E LockPatternUtils: 	at com.android.internal.widget.ILockSettings$Stub$Proxy.setLockCredential(ILockSettings.java:1060)
03-08 09:25:57.608  5703  6004 E LockPatternUtils: 	at com.android.internal.widget.LockPatternUtils.saveLockPassword(LockPatternUtils.java:982)
03-08 09:25:57.608  5703  6004 E LockPatternUtils: 	at com.android.internal.widget.LockPatternUtils.saveLockPassword(LockPatternUtils.java:941)
03-08 09:25:57.608  5703  6004 E LockPatternUtils: 	at com.android.settings.password.ChooseLockPassword$SaveAndFinishWorker.saveAndVerifyInBackground(ChooseLockPassword.java:1103)
03-08 09:25:57.608  5703  6004 E LockPatternUtils: 	at com.android.settings.password.SaveChosenLockWorkerBase$Task.doInBackground(SaveChosenLockWorkerBase.java:119)
03-08 09:25:57.608  5703  6004 E LockPatternUtils: 	at com.android.settings.password.SaveChosenLockWorkerBase$Task.doInBackground(SaveChosenLockWorkerBase.java:115)
03-08 09:25:57.608  5703  6004 E LockPatternUtils: 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
03-08 09:25:57.608  5703  6004 E LockPatternUtils: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
03-08 09:25:57.608  5703  6004 E LockPatternUtils: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
03-08 09:25:57.608  5703  6004 E LockPatternUtils: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
03-08 09:25:57.608  5703  6004 E LockPatternUtils: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
03-08 09:25:57.608  5703  6004 E LockPatternUtils: 	at java.lang.Thread.run(Thread.java:919)
03-08 09:25:57.608  5703  6004 E LockPatternUtils: Caused by: android.os.RemoteException: Remote stack trace:
03-08 09:25:57.608  5703  6004 E LockPatternUtils: 	at com.android.server.locksettings.SyntheticPasswordManager.createPasswordBasedSyntheticPassword(SyntheticPasswordManager.java:660)
03-08 09:25:57.608  5703  6004 E LockPatternUtils: 	at com.android.server.locksettings.LockSettingsService.initializeSyntheticPasswordLocked(LockSettingsService.java:2503)
03-08 09:25:57.608  5703  6004 E LockPatternUtils: 	at com.android.server.locksettings.LockSettingsService.setLockCredentialInternal(LockSettingsService.java:1554)
03-08 09:25:57.608  5703  6004 E LockPatternUtils: 	at com.android.server.locksettings.LockSettingsService.setLockCredential(LockSettingsService.java:1475)
03-08 09:25:57.608  5703  6004 E LockPatternUtils: 	at com.android.internal.widget.ILockSettings$Stub.onTransact(ILockSettings.java:480)
```

**Comment by MarijnS95** [comment]
Can you create a logcat from device startup? Part of the information is likely behind:
```
03-08 09:46:18.964   796   796 I chatty  : uid=1000(system) /system/bin/gatekeeperd expire 54 lines
```
But the gist of it is likely a repeating:
```
03-08 09:48:02.426   796   796 I ServiceManagement: getService: Trying again for android.hardware.gatekeeper@1.0::IGatekeeper/default...
03-08 09:48:03.428   796   796 W ServiceManagement: Waited one second for android.hardware.gatekeeper@1.0::IGatekeeper/default
```
I'd like to know if gatekeeper and the passthrough service are available, and if so the variant being used:
```sh
ls -l /{vendor,odm}/{lib*,bin}/hw/android.hardware.gatekeeper*
```
For completeness, see if Android picks them up too:
```sh
lshal | grep gatekeeper
```
Also, let's make sure the right passthrough service is started:
```sh
cat /vendor/etc/init/*gate*
```

Finally, you may revert https://github.com/sonyxperiadev/device-sony-common/commit/69e4b35232b59b8bce29bf955a96398e27ba1ac2. @ix5 reverted the [cleanup](https://github.com/sonyxperiadev/device-sony-common/commit/26af32cb806028d86cdb1376a0927e2e2db08cff) to align with Android 9 even though we are (IMO) better off to using the AOSP passthrough service.

**Comment by chris42** [comment]
*** BELOW ARE NOT YOSHINO/LILAC INFORMATION ***

Just FYI: I just set a PIN on Kugo (4.9.214 though) without problems (which should include the gatekeeper change of @ix5 ). Maybe my working setup helps to spot any troubles.

"ls -l /{vendor,odm}/{lib*,bin}/hw/android.hardware.gatekeeper*" gives
```
ls: /odm/lib*/hw/android.hardware.gatekeeper*: No such file or directory
ls: /odm/bin/hw/android.hardware.gatekeeper*: No such file or directory
-rwxr-xr-x 1 root shell 11600 2009-01-01 01:00 /vendor/bin/hw/android.hardware.gatekeeper@1.0-service
-rw-r--r-- 1 root root  19956 2009-01-01 01:00 /vendor/lib/hw/android.hardware.gatekeeper@1.0-impl.so
-rw-r--r-- 1 root root  20600 2009-01-01 01:00 /vendor/lib64/hw/android.hardware.gatekeeper@1.0-impl.so
```
"lshal | grep gatekeeper" gives
```
DM,FC Y android.hardware.gatekeeper@1.0::IGatekeeper/default                                      0/1        566    718 453
FC    ? android.hardware.gatekeeper@1.0::IGatekeeper/default           N/A        566    566
FC    ? android.hardware.gatekeeper@1.0::I*/* (/vendor/lib/hw/)           N/A        N/A    
FC    ? android.hardware.gatekeeper@1.0::I*/* (/vendor/lib64/hw/)         N/A        N/A 
```
"cat /vendor/etc/init/*gate*" gives
```
service vendor.gatekeeper-1-0 /vendor/bin/hw/android.hardware.gatekeeper@1.0-service
    class hal
    user system
    group system
```

**Comment by MarijnS95** [comment]
@chris42 That is actually quite interesting. I don't remember the "proprietary" passthrough blobs getting dropped from V9 after https://github.com/sonyxperiadev/device-sony-common/pull/650 got merged, yet the revert from @ix5 tries to use this `-qti` "proprietary" one.

**Comment by stefanhh0** [comment]
Here the requested infos:
[logcat_startup.log](https://github.com/sonyxperiadev/bug_tracker/files/4303122/logcat_startup.log)

```
lilac:/ # ls -l /{vendor,odm}/{lib*,bin}/hw/android.hardware.gatekeeper*
ls: /vendor/lib*/hw/android.hardware.gatekeeper*: No such file or directory
ls: /vendor/bin/hw/android.hardware.gatekeeper*: No such file or directory
-rwxr-xr-x 1 root shell 11032 2019-05-21 11:02 /odm/bin/hw/android.hardware.gatekeeper@1.0-service-qti
-rw-r--r-- 1 root root  24560 2019-05-21 11:02 /odm/lib/hw/android.hardware.gatekeeper@1.0-impl-qti.so
-rw-r--r-- 1 root root  23440 2019-05-21 11:02 /odm/lib64/hw/android.hardware.gatekeeper@1.0-impl-qti.so
```
```
lilac:/ # lshal |grep gatekeeper                                                                                                                                                                                                                                             
FC    ? android.hardware.gatekeeper@1.0::I*/* (/odm/lib/hw/) (-qti)       N/A        N/A    
FC    ? android.hardware.gatekeeper@1.0::I*/* (/odm/lib64/hw/) (-qti)     N/A        N/A  
```
```
lilac:/ # cat /vendor/etc/init/*gate*                                                                                                                                                                                                                                          
service vendor.gatekeeper-1-0 /odm/bin/hw/android.hardware.gatekeeper@1.0-service-qti
    interface android.hardware.gatekeeper@1.0::IGatekeeper default
    class early_hal
    user system
    group system
```

Going to revert that commit you mentioned and will check if it helps.

**Comment by MarijnS95** [comment]
@stefanhh0 Thanks, that reminded me of the issue.

@ix5 Reverted the cleanup in common, but forgot to revert the cleanup in sepolicy: https://github.com/sonyxperiadev/device-sony-sepolicy/pull/543.

If you check dmesg you'll see that Android fails to start `/odm/bin/hw/android.hardware.gatekeeper@1.0-service-qti` because it is "unlabeled" (or rather, it is labeled but that label is unknown within the current policy).

Reverting that should do the trick. I'll ask @jerpelea to pop that last commit off.

**Comment by stefanhh0** [comment]
Reverting the 2 commits from https://github.com/sonyxperiadev/device-sony-sepolicy/pull/543 fixed the problem. Thanks for your help, I'll keep this one open until you've integrated the cleanup of those two repos resp. decided to revert it. 

I'd agree to have the cleanup as well for legacy rather than reverting it esp. when it is a valid thing to do. Additionally legacy stays that way closer to master which is probably a good thing.

**Comment by MarijnS95** [comment]
@stefanhh0 Can you try the other way around too? That is, **keep** the commits from https://github.com/sonyxperiadev/device-sony-sepolicy/pull/543 and revert/delete https://github.com/sonyxperiadev/device-sony-common/commit/69e4b35232b59b8bce29bf955a96398e27ba1ac2?
That's the cleaned up situation we'd like to end up (or rather, stay) on.

**Comment by stefanhh0** [comment]
Works as well fine! So the change would be safe. Also upgraded now using android-10.0.0_r30 which was the initial reason to rebuild :-)

**Comment by MarijnS95** [comment]
@stefanhh0 Great, as expected :smile: 

I wanted to ask whether you ran `m installclean` inbetween to clean up stray `.rc` files, but a full rebuild without previous `out` folder will do as well.

**Comment by wyzco** [comment]
> Works as well fine! So the change would be safe. Also upgraded now using android-10.0.0_r30 which was the initial reason to rebuild :-)

Does 4.9 kernel still have fingerprint issue(random reboot)?

**Comment by stefanhh0** [comment]
Not using it, and haven't tried it for a while. However I think FPC issues are still there and have not yet been fixed.

**Comment by stefanhh0** [comment]
The commit that introduces the problem has been removed.

**Comment by Roker2** [comment]
Hi! How did you fix it?

**Comment by stefanhh0** [comment]
See: https://github.com/sonyxperiadev/bug_tracker/issues/557#issuecomment-596207161
