### ISSUE TITLE
[Seine][pdx201] Camera application crash unable to detect video qualities

### ISSUE THREAD

**Issue by AngryGami** [sonyxperiadev/bug_tracker#618]
**Platform:** Seine
**Device:** pdx201
**Kernel version:** 4.14
**Android version:** 10
**Software binaries version:** SW_binaries_for_Xperia_Android_10.0.7.1_r1_v9c_seine

**Previously working on**
I does "work" in emulator at least with vitual scene, which probably confirms that this is hardware related issue.

**Description**
Write the issue description here.

**Symptoms**
```
2020-07-15 22:42:54.491 8981-8981/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.android.camera2, PID: 8981
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.camera2/com.android.camera.CameraActivity}: java.lang.IllegalArgumentException: Could not find supported video qualities.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalArgumentException: Could not find supported video qualities.
        at com.android.camera.settings.SettingsUtil.getNextSupportedVideoQualityIndex(SettingsUtil.java:347)
        at com.android.camera.settings.SettingsUtil.getSelectedVideoQualities(SettingsUtil.java:319)
        at com.android.camera.settings.PictureSizeLoader.computeQualitiesForCamera(PictureSizeLoader.java:154)
        at com.android.camera.settings.PictureSizeLoader.computePictureSizes(PictureSizeLoader.java:120)
        at com.android.camera.CameraActivity.onCreateTasks(CameraActivity.java:1509)
        at com.android.camera.util.QuickActivity.onCreate(QuickActivity.java:114)
        at android.app.Activity.performCreate(Activity.java:7825)
        at android.app.Activity.performCreate(Activity.java:7814)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

**How to reproduce**
Just run camera app.

**Comment by AngryGami** [comment]
Can someone at least confirm this is not only happening for me?

**Comment by ix5** [comment]
pdx201 is in early stages of porting. Have you traced the missing video stream enumeration into deeper layers of the camera framework?

**Comment by AngryGami** [comment]
Camera works now... Don't know what fixed it but it doesn't matter that much. :)

**Comment by MarijnS95** [comment]
@AngryGami It wasn't fixed but inadvertently worked around by disabling the "broken" wide angle camera: https://github.com/sonyxperiadev/device-sony-pdx201/pull/15

We're currently investigating why this camera is not exposing video modes when it should.

**Comment by AngryGami** [comment]
For my limited usecase this is fine :)
