### ISSUE TITLE
[TONE][Kernel 4.14][Android v10.0.0_r15] Errors during build

### ISSUE THREAD

**Issue by izakhartchouk** [sonyxperiadev/bug_tracker#625]
- Platform: Tone
- Device Code Name: Dora
- Kernel version: 4.14
- Android version: 10.0.0_r15

I'm trying to build Android 10 and flash it on Sony Xperia X Performance Dual according to this [developer.sony.com](https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-android-10-0-0) guide.

Sony Xperia X Performance has platform: `Tone`, which is supported by Android 10, see this [software binaries list](https://developer.sony.com/develop/open-devices/downloads/software-binaries). I've downloaded this software binary for AOSP build SW_BINARIES_FOR_XPERIA_ANDROID_10.0.7.1_R1_V7A_TONE.ZIP.

The problem is when I enter command `make -j$(nproc)`, I'm getting errors:
```cmd
[ 99% 580/581] finishing build rules ...
FAILED:
vendor/qcom/opensource/location/gnsspps/Android.mk: error: "libgnsspps (SHARED_LIBRARIES android-arm64) missing libgps.utils (SHARED_LIBRARIES android-arm64)"
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
vendor/qcom/opensource/location/gnsspps/Android.mk: error: "libgnsspps (SHARED_LIBRARIES android-arm) missing libgps.utils (SHARED_LIBRARIES android-arm)"
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
vendor/qcom/opensource/location/loc_api/ds_api/Android.mk: error: "libloc_ds_api (SHARED_LIBRARIES android-arm64) missing libgps.utils (SHARED_LIBRARIES android-arm64)"
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
vendor/qcom/opensource/location/loc_api/ds_api/Android.mk: error: "libloc_ds_api (SHARED_LIBRARIES android-arm) missing libgps.utils (SHARED_LIBRARIES android-arm)"
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
vendor/qcom/opensource/location/loc_api/loc_api_v02/Android.mk: error: "libloc_api_v02 (SHARED_LIBRARIES android-arm64) missing libloc_core (SHARED_LIBRARIES android-arm64)"
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
vendor/qcom/opensource/location/loc_api/loc_api_v02/Android.mk: error: "libloc_api_v02 (SHARED_LIBRARIES android-arm64) missing libgps.utils (SHARED_LIBRARIES android-arm64)"
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
vendor/qcom/opensource/location/loc_api/loc_api_v02/Android.mk: error: "libloc_api_v02 (SHARED_LIBRARIES android-arm) missing libloc_core (SHARED_LIBRARIES android-arm)"
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
vendor/qcom/opensource/location/loc_api/loc_api_v02/Android.mk: error: "libloc_api_v02 (SHARED_LIBRARIES android-arm) missing libgps.utils (SHARED_LIBRARIES android-arm)"
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
build/make/core/main.mk:1008: error: exiting from previous errors.
12:02:20 ckati failed with: exit status 1
```

How to resolve that and proceed further? Please, let me know, if I missed something to mention.

**Comment by stefanhh0** [comment]
Hey @izakhartchouk development of tone had to be stopped unfortunately on k4.14. 

However, it is possible using k4.9 and android 10 and choosing the latest k4.9 SW binaries: SW_binaries_for_Xperia_Android_9.0_2.3.2_v9_tone.zip

I have a script that helps building the version:
https://github.com/stefanhh0/aosp-10/blob/master/build-4.9.sh

I don't know if it still is working, since I haven't done such a build in a long time. However your can give it a try.

**Comment by izakhartchouk** [comment]
@stefanhh0, thanks for the advice, but I'm a beginner in this Android configuring stuff :)
What branch of Android can I pick to follow [developer.sony.com](https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-android-10-0-0) guide OR can you, please, describe how and where to use your script?

**Comment by stefanhh0** [comment]
There is a description here: https://github.com/stefanhh0/aosp-10, and also the script shows the help, when started with -h

In your case you should try following, go to $SOURCE/.repo/local_manifests and switch to the 10 legacy branch: `git checkout android-10_legacy`

Afterwards do a `repo sync` in the source root directory.

Then call the script as follows:

`env LUNCH_CHOICE=aosp_f8131-userdebug SOURCE=<PATH_TO_YOUR_SOURCES> ./build-4.9.sh -b android-10.0.0_r40 -k`

f8131 is for single SIM. If you have a dual SIM you have to use f8132 instead.

**Comment by izakhartchouk** [comment]
@stefanhh0, I've tried to init repo for android-10_legacy branhc, but got an error:
```cmd
user@host:~/android$ repo init -u https://android.googlesource.com/platform/manifest -b android-10_legacy
Downloading Repo source from https://gerrit.googlesource.com/git-repo
remote: Finding sources: 100% (7/7)
remote: Total 7 (delta 0), reused 7 (delta 0)
Unpacking objects: 100% (7/7), 41.06 KiB | 1.64 MiB/s, done.
Downloading manifest from https://android.googlesource.com/platform/manifest
Receiving objects: 100% (79084/79084), 59.48 MiB | 59.89 MiB/s, done.
Resolving deltas: 100% (23498/23498), done.
fatal: couldn't find remote ref refs/heads/android-10_legacy
manifests:
fatal: couldn't find remote ref refs/heads/android-10_legacy
```

**Comment by stefanhh0** [comment]
Okay, thought you already have the repo, use following commands to create it from scratch and build for your phone:

```
repo init -u https://android.googlesource.com/platform/manifest -b android-10.0.0_r40
cd .repo
git clone https://github.com/sonyxperiadev/local_manifests
cd local_manifests
git checkout android-10_legacy
cd ../..
repo sync
./repo_update.sh
env LUNCH_CHOICE=aosp_f8131-userdebug SOURCE=<PATH_TO_YOUR_SOURCES> ./build-4.9.sh
```

**Comment by izakhartchouk** [comment]
@stefanhh0, execution of your script finished with this:
```cmd
remote: Finding sources: 100% (9/9)
remote: Total 9 (delta 3), reused 9 (delta 3)
Unpacking objects: 100% (9/9), 33.41 KiB | 698.00 KiB/s, done.
From https://android.googlesource.com/platform/manifest
   d7481122f..83d6f1f2f  oreo-mr1-vts-release -> origin/oreo-mr1-vts-release
   ae73feb26..2b1f0c48a  oreo-vts-release     -> origin/oreo-vts-release
   e43f3563a..66bb42fe8  pie-vts-release      -> origin/pie-vts-release
Already up to date.
~/android
~/android/.repo/local_manifests ~/android
HEAD is now at 78b3edc broadcom: sync branches with android version
~/android
~/android/device/sony/tone ~/android
HEAD is now at 1faa78d Merge pull request #197 from MarijnS95/ueventd-read-firmware_mnt
~/android
~/android/device/sony/common ~/android
HEAD is now at 607d461 CommonConfig: Drop legacy/unstable /firmware symlink
~/android
~/android/device/sony/sepolicy ~/android
HEAD is now at 45fb8d9 seapp_contexts: qcrilam runs as normal app user now
~/android
~/android/kernel/sony/msm-4.9/common-kernel ~/android
HEAD is now at 9f991bc update prebuilt kernel [2.3.2.r1.4] Linux 4.9.213
~/android
~/android/kernel/sony/msm-4.9/kernel ~/android
HEAD is now at 5abe775f993c Merge pull request #2244 from stefanhh0/4.9.221
~/android
~/android/vendor/oss/fingerprint ~/android
HEAD is now at bd1c46d egistec: SaveTemplate returns the size on Kumano + Seine
~/android
~/android/vendor/oss/transpower ~/android
HEAD is now at cc3e230 Bump app version (2.2.2)
~/android
~/android/vendor/qcom/opensource/location ~/android
HEAD is now at eabdf14 Android.mk: Make q-mr0 guard 4.9-only
~/android
~/android/.repo/local_manifests ~/android
rm: cannot remove 'LA.UM.7.1.r1.xml': No such file or directory
```
Is that a successfull end of execution? I've found that inside /.repo/local_manifests there is a similar file with different name `LE.UM.2.3.2.r1.4.xml`

**Comment by stefanhh0** [comment]
That wasn't successful. I have pushed an updated version of  the file, please retry with the latest version of the script. When on the legacy branch, the local manifest must not be patched. That has been fixed. See as well commit: https://github.com/stefanhh0/aosp-10/commit/224807ec3ae21ccff59bf2bde2c11dfec6223d1d

**Comment by izakhartchouk** [comment]
@stefanhh0, this time I've got another error: `error.GitError: Cannot initialize work tree for all`
```cmd
hardware/qcom/media/: discarding 3 commits
packages/apps/DeskClock/: discarding 1 commits
packages/apps/Messaging/: discarding 1 commits
system/extras/: discarding 1 commits
system/sepolicy/: discarding 1 commits
Checking out projects:  96% (681/706) aosp_buildgit-lfs filter-process --skip: 1: git-lfs: not found
fatal: the remote end hung up unexpectedly
error: Cannot checkout all: GitError: Cannot initialize work tree for all
Traceback (most recent call last):
  File "/home/slasher/android/.repo/repo/main.py", line 628, in <module>
    _Main(sys.argv[1:])
  File "/home/slasher/android/.repo/repo/main.py", line 602, in _Main
    result = run()
  File "/home/slasher/android/.repo/repo/main.py", line 595, in <lambda>
    run = lambda: repo._Run(name, gopts, argv) or 0
  File "/home/slasher/android/.repo/repo/main.py", line 264, in _Run
    result = cmd.Execute(copts, cargs)
  File "/home/slasher/android/.repo/repo/subcmds/sync.py", line 982, in Execute
    self._Checkout(all_projects, opt, err_event, err_results)
  File "/home/slasher/android/.repo/repo/subcmds/sync.py", line 567, in _Checkout
    self._CheckoutWorker(**kwargs)
  File "/home/slasher/android/.repo/repo/subcmds/sync.py", line 447, in _CheckoutWorker
    return self._CheckoutOne(opt, project, *args, **kwargs)
  File "/home/slasher/android/.repo/repo/subcmds/sync.py", line 481, in _CheckoutOne
    project.Sync_LocalHalf(syncbuf, force_sync=opt.force_sync)
  File "/home/slasher/android/.repo/repo/project.py", line 1623, in Sync_LocalHalf
    self._InitWorkTree(force_sync=force_sync, submodules=submodules)
  File "/home/slasher/android/.repo/repo/project.py", line 3135, in _InitWorkTree
    raise GitError('Cannot initialize work tree for ' + self.name)
error.GitError: Cannot initialize work tree for all
```

**Comment by stefanhh0** [comment]
`Checking out projects:  96% (681/706) aosp_buildgit-lfs filter-process --skip: 1: git-lfs: not found`

That is the problem, you have to either install git-lfs or you have to comment-out the opengapps stuff in case you are not interested.
