### ISSUE TITLE
[Seine|Ganges][pdx201|kirin] Logs of the device are filled with "Failed to parse network stats" exceptions

### ISSUE THREAD

**Issue by AngryGami** [sonyxperiadev/bug_tracker#641]
**Platform:** Seine and Ganges
**Device:** pdx201 and kirin
**Kernel version:** 4.14
**Android version:**  10
**Software binaries version:** latest available

**Previously working on**
Probably Android 9.

**Description**
There is something going on in with either wifi or networking in general on this version of Android for these devices because there is constant stream (not overwhelming but pretty consistent) of exceptions like these:
```
10-26 08:58:41.977  1265  1614 E NetworkStats: java.lang.IllegalStateException: java.io.IOException: Failed to parse network stats
10-26 08:58:41.977  1265  1614 E NetworkStats: 	at com.android.server.NetworkManagementService.getNetworkStatsUidDetail(NetworkManagementService.java:1551)
10-26 08:58:41.977  1265  1614 E NetworkStats: 	at com.android.server.net.NetworkStatsService.getNetworkStatsUidDetail(NetworkStatsService.java:1666)
10-26 08:58:41.977  1265  1614 E NetworkStats: 	at com.android.server.net.NetworkStatsService.recordSnapshotLocked(NetworkStatsService.java:1256)
10-26 08:58:41.977  1265  1614 E NetworkStats: 	at com.android.server.net.NetworkStatsService.performPollLocked(NetworkStatsService.java:1343)
10-26 08:58:41.977  1265  1614 E NetworkStats: 	at com.android.server.net.NetworkStatsService.updateIfacesLocked(NetworkStatsService.java:1164)
10-26 08:58:41.977  1265  1614 E NetworkStats: 	at com.android.server.net.NetworkStatsService.updateIfaces(NetworkStatsService.java:1141)
10-26 08:58:41.977  1265  1614 E NetworkStats: 	at com.android.server.net.NetworkStatsService.forceUpdateIfaces(NetworkStatsService.java:869)
10-26 08:58:41.977  1265  1614 E NetworkStats: 	at com.android.server.ConnectivityService.notifyIfacesChangedForNetworkStats(ConnectivityService.java:6822)
10-26 08:58:41.977  1265  1614 E NetworkStats: 	at com.android.server.ConnectivityService.updateLinkProperties(ConnectivityService.java:5575)
10-26 08:58:41.977  1265  1614 E NetworkStats: 	at com.android.server.ConnectivityService.updateNetworkInfo(ConnectivityService.java:6553)
10-26 08:58:41.977  1265  1614 E NetworkStats: 	at com.android.server.ConnectivityService.handleRegisterNetworkAgent(ConnectivityService.java:5527)
10-26 08:58:41.977  1265  1614 E NetworkStats: 	at com.android.server.ConnectivityService.access$4100(ConnectivityService.java:230)
10-26 08:58:41.977  1265  1614 E NetworkStats: 	at com.android.server.ConnectivityService$InternalHandler.handleMessage(ConnectivityService.java:3772)
10-26 08:58:41.977  1265  1614 E NetworkStats: 	at android.os.Handler.dispatchMessage(Handler.java:107)
10-26 08:58:41.977  1265  1614 E NetworkStats: 	at android.os.Looper.loop(Looper.java:214)
10-26 08:58:41.977  1265  1614 E NetworkStats: 	at android.os.HandlerThread.run(HandlerThread.java:67)
10-26 08:58:41.977  1265  1614 E NetworkStats: Caused by: java.io.IOException: Failed to parse network stats
10-26 08:58:41.977  1265  1614 E NetworkStats: 	at com.android.server.net.NetworkStatsFactory.readNetworkStatsDetail(NetworkStatsFactory.java:357)
10-26 08:58:41.977  1265  1614 E NetworkStats: 	at com.android.server.NetworkManagementService.getNetworkStatsUidDetail(NetworkManagementService.java:1549)
10-26 08:58:41.977  1265  1614 E NetworkStats: 	... 15 more
```
or
```
10-26 08:58:52.228  1265  1390 E BatteryExternalStatsWorker: Error updating external stats: 
10-26 08:58:52.228  1265  1390 E BatteryExternalStatsWorker: java.lang.IllegalStateException: java.io.IOException: Failed to parse network stats
10-26 08:58:52.228  1265  1390 E BatteryExternalStatsWorker: 	at com.android.server.NetworkManagementService.getNetworkStatsUidDetail(NetworkManagementService.java:1551)
10-26 08:58:52.228  1265  1390 E BatteryExternalStatsWorker: 	at com.android.server.net.NetworkStatsService.getNetworkStatsUidDetail(NetworkStatsService.java:1666)
10-26 08:58:52.228  1265  1390 E BatteryExternalStatsWorker: 	at com.android.server.net.NetworkStatsService.getDetailedUidStats(NetworkStatsService.java:812)
10-26 08:58:52.228  1265  1390 E BatteryExternalStatsWorker: 	at com.android.internal.os.BatteryStatsImpl.readNetworkStatsLocked(BatteryStatsImpl.java:10695)
10-26 08:58:52.228  1265  1390 E BatteryExternalStatsWorker: 	at com.android.internal.os.BatteryStatsImpl.updateMobileRadioState(BatteryStatsImpl.java:11017)
10-26 08:58:52.228  1265  1390 E BatteryExternalStatsWorker: 	at com.android.server.am.BatteryExternalStatsWorker.updateExternalStatsLocked(BatteryExternalStatsWorker.java:512)
10-26 08:58:52.228  1265  1390 E BatteryExternalStatsWorker: 	at com.android.server.am.BatteryExternalStatsWorker.access$900(BatteryExternalStatsWorker.java:62)
10-26 08:58:52.228  1265  1390 E BatteryExternalStatsWorker: 	at com.android.server.am.BatteryExternalStatsWorker$1.run(BatteryExternalStatsWorker.java:362)
10-26 08:58:52.228  1265  1390 E BatteryExternalStatsWorker: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
10-26 08:58:52.228  1265  1390 E BatteryExternalStatsWorker: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10-26 08:58:52.228  1265  1390 E BatteryExternalStatsWorker: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
10-26 08:58:52.228  1265  1390 E BatteryExternalStatsWorker: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-26 08:58:52.228  1265  1390 E BatteryExternalStatsWorker: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-26 08:58:52.228  1265  1390 E BatteryExternalStatsWorker: 	at com.android.server.am.BatteryExternalStatsWorker.lambda$new$0(BatteryExternalStatsWorker.java:80)
10-26 08:58:52.228  1265  1390 E BatteryExternalStatsWorker: 	at com.android.server.am.-$$Lambda$BatteryExternalStatsWorker$ddVY5lmqswnSjXppAxPTOHbuzzQ.run(Unknown Source:2)
10-26 08:58:52.228  1265  1390 E BatteryExternalStatsWorker: 	at java.lang.Thread.run(Thread.java:919)
10-26 08:58:52.228  1265  1390 E BatteryExternalStatsWorker: Caused by: java.io.IOException: Failed to parse network stats
10-26 08:58:52.228  1265  1390 E BatteryExternalStatsWorker: 	at com.android.server.net.NetworkStatsFactory.readNetworkStatsDetail(NetworkStatsFactory.java:357)
10-26 08:58:52.228  1265  1390 E BatteryExternalStatsWorker: 	at com.android.server.NetworkManagementService.getNetworkStatsUidDetail(NetworkManagementService.java:1549)
10-26 08:58:52.228  1265  1390 E BatteryExternalStatsWorker: 	... 15 more
```
Note that these are from two (at least what I've seen so far) different loggers: BatteryExternalStatsWorker and NetworkStats.

**How to reproduce**
Nothing need to be done - it is just there.

**Additional context**
Wifi and data connectivity on these devices is working very unstable so it might be that this exceptions are somehow related.

**Comment by ix5** [comment]
Sorry I'm late to the party, but I'll pile onto this so I won't forget.

Networks stats are a real annoyance. They are afaicr not implemented on the vendor side, so you'll have lots of warnings popping up such as:

```
06-01 03:34:36.190  1054  1257 E WifiVendorHal: enableLinkLayerStats(l.1063) failed {.code = ERROR_NOT_SUPPORTED, .description = }
06-01 03:34:36.191  1054  1257 E WifiVendorHal: unable to enable link layer stats collection
06-01 03:34:36.191  1054  1257 D WificondControl: Setting up interface for client mode
```
or
```
11324:02-01 23:49:08.532  1075  1243 E WifiVendorHal: getWifiLinkLayerStats_1_3_Internal(l.932) failed {.code = ERROR_NOT_SUPPORTED, .description = }
6782:02-07 21:53:56.324   969   969 E WifiClientModeImpl: getWifiLinkLayerStats called without an interface
```

Regarding your issue: I vaguely remember something with eBPF support? But I can't offer any more assistance beyond following the codepaths.

https://android.googlesource.com/platform/frameworks/base/+/refs/tags/android-10.0.0_r41/services/core/java/com/android/server/net/NetworkStatsFactory.java#348
https://android.googlesource.com/platform/frameworks/base/+/refs/tags/android-10.0.0_r41/services/core/java/com/android/server/net/NetworkStatsFactory.java#357

**Comment by jerpelea** [comment]
the latest release should have addressed the log spam

**Comment by AngryGami** [comment]
@jerpelea What exactly do you mean by "latest release"? My build for Android 10 pdx201 device still have these messages in the log. I've updated my repository April 12.
