### ISSUE TITLE
Fail to build AOSP for Xperia XA2 

### ISSUE THREAD

**Issue by tl3gr4nd** [sonyxperiadev/bug_tracker#714]
**Platform:** 
**Device: Sony Xperia XA2 (pioneer)** 
**Kernel version:** 
**Android version: 11.0.0_r40** 
**Software binaries version:** 

Hello,
I followed the following guide but I have an error during the execution of avbtool when I do `make -j12` : https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-android-11-0-0#tutorial-step-4.

I have the same error when I just `make`.

Here are the last console log for my very last try:
```
[fox@fedora android]$ make -j2
19:52:43 ************************************************************
19:52:43 You are building on a machine with 15.5GB of RAM
19:52:43 
19:52:43 The minimum required amount of free memory is around 16GB,
19:52:43 and even with that, some configurations may not work.
19:52:43 
19:52:43 If you run into segfaults or other errors, try reducing your
19:52:43 -j value.
19:52:43 ************************************************************
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=11
TARGET_PRODUCT=aosp_h3113
TARGET_BUILD_VARIANT=user
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=generic
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv8-a
TARGET_2ND_CPU_VARIANT=generic
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-5.13.12-200.fc34.x86_64-x86_64-Fedora-34-(KDE-Plasma)
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=RQ3A.210805.001.A1
OUT_DIR=out
PRODUCT_SOONG_NAMESPACES=device/sony/common device/sony/nile vendor/qcom/opensource/core-utils vendor/qcom/opensource/display/sm8150 vendor/qcom/opensource/display-commonsys-intf/sm8150
============================================
[  0% 4/53389] //libcore/apex:com.android.i18n apex (image) [common]
FAILED: out/soong/.intermediates/libcore/apex/com.android.i18n/android_common_com.android.i18n_image/com.android.i18n.apex.unsigned
rm -rf out/soong/.intermediates/libcore/apex/com.android.i18n/android_common_com.android.i18n_image/image.apex && mkdir -p out/soong/.intermediates/libcore/apex/com.android.i18n/android_common_com.android.i18n_image/image.apex && (. out/soong/.intermediates/libcore/apex/com.android.i18n/android_common_com.android.i18n_image/com.android.i18n.apex.unsigned.copy_commands) && APEXER_TOOL_PATH=out/soong/host/linux-x86/bin:prebuilts/sdk/tools/linux/bin out/soong/host/linux-x86/bin/apexer --force --manifest out/soong/.intermediates/libcore/apex/com.android.i18n/android_common_com.android.i18n_image/apex_manifest.pb --file_contexts system/sepolicy/apex/com.android.i18n-file_contexts --canned_fs_config out/soong/.intermediates/libcore/apex/com.android.i18n/android_common_com.android.i18n_image/canned_fs_config --include_build_info --payload_type image --key libcore/apex/com.android.i18n.pem --pubkey libcore/apex/com.android.i18n.avbpubkey --target_sdk_version 30 --min_sdk_version 30 --no_hashtree out/soong/.intermediates/libcore/apex/com.android.i18n/android_common_com.android.i18n_image/image.apex out/soong/.intermediates/libcore/apex/com.android.i18n/android_common_com.android.i18n_image/com.android.i18n.apex.unsigned 
Traceback (most recent call last):
  File "/run/media/fox/27fa48cb-b194-4e9e-9462-fdc86b6cdb97/android/out/soong/host/linux-x86/bin/avbtool/internal/stdlib/runpy.py", line 174, in _run_module_as_main
  File "/run/media/fox/27fa48cb-b194-4e9e-9462-fdc86b6cdb97/android/out/soong/host/linux-x86/bin/avbtool/internal/stdlib/runpy.py", line 72, in _run_code
  File "/run/media/fox/27fa48cb-b194-4e9e-9462-fdc86b6cdb97/android/out/soong/host/linux-x86/bin/avbtool/__main__.py", line 12, in <module>
  File "/run/media/fox/27fa48cb-b194-4e9e-9462-fdc86b6cdb97/android/out/soong/host/linux-x86/bin/avbtool/internal/stdlib/runpy.py", line 174, in _run_module_as_main
  File "/run/media/fox/27fa48cb-b194-4e9e-9462-fdc86b6cdb97/android/out/soong/host/linux-x86/bin/avbtool/internal/stdlib/runpy.py", line 72, in _run_code
  File "/run/media/fox/27fa48cb-b194-4e9e-9462-fdc86b6cdb97/android/out/soong/host/linux-x86/bin/avbtool/avbtool.py", line 4648, in <module>
  File "/run/media/fox/27fa48cb-b194-4e9e-9462-fdc86b6cdb97/android/out/soong/host/linux-x86/bin/avbtool/avbtool.py", line 4475, in run
  File "/run/media/fox/27fa48cb-b194-4e9e-9462-fdc86b6cdb97/android/out/soong/host/linux-x86/bin/avbtool/avbtool.py", line 4567, in add_hashtree_footer
  File "/run/media/fox/27fa48cb-b194-4e9e-9462-fdc86b6cdb97/android/out/soong/host/linux-x86/bin/avbtool/avbtool.py", line 3583, in add_hashtree_footer
  File "/run/media/fox/27fa48cb-b194-4e9e-9462-fdc86b6cdb97/android/out/soong/host/linux-x86/bin/avbtool/avbtool.py", line 2987, in _generate_vbmeta_blob
  File "/run/media/fox/27fa48cb-b194-4e9e-9462-fdc86b6cdb97/android/out/soong/host/linux-x86/bin/avbtool/avbtool.py", line 411, in encode_rsa_key
  File "/run/media/fox/27fa48cb-b194-4e9e-9462-fdc86b6cdb97/android/out/soong/host/linux-x86/bin/avbtool/avbtool.py", line 370, in __init__
  File "/run/media/fox/27fa48cb-b194-4e9e-9462-fdc86b6cdb97/android/out/soong/host/linux-x86/bin/avbtool/internal/stdlib/subprocess.py", line 394, in __init__
  File "/run/media/fox/27fa48cb-b194-4e9e-9462-fdc86b6cdb97/android/out/soong/host/linux-x86/bin/avbtool/internal/stdlib/subprocess.py", line 1047, in _execute_child
OSError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/run/media/fox/27fa48cb-b194-4e9e-9462-fdc86b6cdb97/android/out/soong/host/linux-x86/bin/apexer/internal/stdlib/runpy.py", line 174, in _run_module_as_main
  File "/run/media/fox/27fa48cb-b194-4e9e-9462-fdc86b6cdb97/android/out/soong/host/linux-x86/bin/apexer/internal/stdlib/runpy.py", line 72, in _run_code
  File "/run/media/fox/27fa48cb-b194-4e9e-9462-fdc86b6cdb97/android/out/soong/host/linux-x86/bin/apexer/__main__.py", line 12, in <module>
  File "/run/media/fox/27fa48cb-b194-4e9e-9462-fdc86b6cdb97/android/out/soong/host/linux-x86/bin/apexer/internal/stdlib/runpy.py", line 174, in _run_module_as_main
  File "/run/media/fox/27fa48cb-b194-4e9e-9462-fdc86b6cdb97/android/out/soong/host/linux-x86/bin/apexer/internal/stdlib/runpy.py", line 72, in _run_code
  File "/run/media/fox/27fa48cb-b194-4e9e-9462-fdc86b6cdb97/android/out/soong/host/linux-x86/bin/apexer/apexer.py", line 708, in <module>
  File "/run/media/fox/27fa48cb-b194-4e9e-9462-fdc86b6cdb97/android/out/soong/host/linux-x86/bin/apexer/apexer.py", line 701, in main
  File "/run/media/fox/27fa48cb-b194-4e9e-9462-fdc86b6cdb97/android/out/soong/host/linux-x86/bin/apexer/apexer.py", line 561, in CreateApex
  File "/run/media/fox/27fa48cb-b194-4e9e-9462-fdc86b6cdb97/android/out/soong/host/linux-x86/bin/apexer/apexer.py", line 200, in RunCommand
AssertionError: Failed to execute: out/soong/host/linux-x86/bin/avbtool add_hashtree_footer --do_not_generate_fec --algorithm SHA256_RSA4096 --hash_algorithm sha256 --key libcore/apex/com.android.i18n.pem --prop apex.key:com.android.i18n --salt 7e147e5ada41075db6639e2ffe2728b402010a68fc6264a77eff60f799841aa1 --image /run/media/fox/27fa48cb-b194-4e9e-9462-fdc86b6cdb97/android/out/soong/.temp/tmpDxNSxN/content/apex_payload.img --no_hashtree
19:52:48 ninja failed with: exit status 1
```

And I have attached the generated logs I found in the `out/` directory :
[error.log](https://github.com/sonyxperiadev/bug_tracker/files/7086215/error.log)
[soong.log](https://github.com/sonyxperiadev/bug_tracker/files/7086216/soong.log)

One last thing: in the guide, it is mentioned the use of `make -j$(nproc)` but when I `echo $nproc`, nothing is returned. Is it a mistake in the guide? And in a previous step, the use of the `repo` command is not followed by its `-j` argument either.

**Comment by MarijnS95** [comment]
> One last thing: in the guide, it is mentioned the use of `make -j$(nproc)` but when I `echo $nproc`, nothing is returned. Is it a mistake in the guide?

The build guide clearly calls for `$(nproc)` (executing a command in a sub-shell), why replace that with `$nproc` (evaluating a possible variable)? You can call this program directly:

```console
$ nproc
64
```

> And in a previous step, the use of the `repo` command is not followed by its `-j` argument either.

Does it need to?

```console
$  repo sync -h | rg jobs -A1
  -j JOBS, --jobs=JOBS  number of jobs to run in parallel (default: 4; based
                        on number of CPU cores)
...
```

**Comment by tl3gr4nd** [comment]
> > One last thing: in the guide, it is mentioned the use of `make -j$(nproc)` but when I `echo $nproc`, nothing is returned. Is it a mistake in the guide?
> 
> The build guide clearly calls for `$(nproc)` (executing a command in a sub-shell), why replace that with `$nproc` (evaluating a possible variable)? You can call this program directly:
> 
> ```
> $ nproc
> 64
> ```
> 
> Note that this is unnecessary. AOSP soong already runs on all threads, and spawns many more for certain sub-tasks too. `-j` only makes a difference if trying to spawn many more or way less (in case of too little memory) tasks at once.
> 
> > And in a previous step, the use of the `repo` command is not followed by its `-j` argument either.
> 
> Does it need to?
> 
> ```
> $  repo sync -h | rg jobs -A1
>   -j JOBS, --jobs=JOBS  number of jobs to run in parallel (default: 4; based
>                         on number of CPU cores)
> ...
> ```

And... this becomes awkward... :D
I did not step back to think that `proc` was a binary and I sticked to the idea it was a environment variable because of the previous command which  source a bash script called `envsetup`. I feel... not very clever for this one :s

**Comment by tl3gr4nd** [comment]
OK. I found the problem which was... I did not have the package`openssl` installed.
Actually, to install the dependency needed to build an Android, I installed the ones from the following script: https://gist.github.com/axxx007xxxz/60fea50f4b123e0163f972d1709068c2 because I am on Fedora. But only `openssl-dev` was installed.
After verification, `openssl` was not listed in the needed dependencies from the guide: https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-android-11-0-0#tutorial-step-1.

What I did to find out was to notice that the command `openssl` was executed by `avbtool`. The stack trace did not point which command was executed (or at least, tried to be) but was kind enough to give the line and the source file name : we can then deduce that the source was line 370 in `external/avb/avbtool.py` where we can see that the `args` variable mentions 'openssl'.

**Comment by Espionage724** [comment]
I ran into an unrelated issue on Fedora 38 with `avbtool`. I installed openssl1.1 and that didn't work. Saw this thread,thought surely `openssl` by itself would be installed but tried it anyway and it wasn't.

In Aug 2023 on Fedora 38 I had to manually install the `openssl` package for `avbtool` to work.
